In [1]:
import os
import json
import pandas as pd
from typing import Dict

from autogen import AssistantAgent, UserProxyAgent, GroupChat, GroupChatManager
from autogen.coding import LocalCommandLineCodeExecutor

In [2]:
OPENDS_NAME             = "CAN"
TASK                    = "join"

# the dataset (stored as an archive, it's large)
DATASET_PATH            = f"../data/datasets/datasets_{OPENDS_NAME}.zip"

# the Ground Truth file with table paris (from LakeBench)
GT_PATH                 = f"../data/{TASK}/{OPENDS_NAME}_ground_truth.csv"

# the clusters of tables obtained by tables_clustering.ipynb
CLUSTERS_PATH           = f'../data/{TASK}/clusters/clusters_{OPENDS_NAME}.json'

# the directory where are stored for each table a small snapshot (<5) of its rows
REPR_ROWS_DIR_PATH      = f'../data/representative_rows/{OPENDS_NAME}'

# the queries created, in a CSV file with fields
# NL-question, NL-human-like-question, SQL-query, table1-id, table2-id
RESULTS_PATH            = f'../data/queries/{OPENDS_NAME}.csv'

# Used to select the representative rows (by now, they are just randomly sampled)
MAX_UNIQUE_VALUES       = 10

# the number of rows to consider as an example snapshot 
# passed to the generator agent
N_REPRESENTATIVE_ROWS   = 3

# the number of queries that we want to generate for each pair of table
N_QUERIES_PER_PAIR      = 3

In [24]:
if not os.path.isdir(os.path.dirname(RESULTS_PATH)):
    os.makedirs(os.path.dirname(RESULTS_PATH))

In [3]:
import unicodedata

def sanitize_string(s):
    """
    Replaces problematic characters in column names with underscores,
    normalizes accents, and strips spaces.
    """
    if not isinstance(s, str):
        return s
    
    # Normalize accents (e.g., é -> e)
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('utf-8')
    # Replace problematic characters with underscores
    return s.replace('\n', '_').replace(' ', '_').replace('.', '_').replace('"', '_').strip()
    
def sanitize_all_strings(strings):
    """
    Replaces problematic characters in column names with underscores,
    normalizes accents, and strips spaces.
    """
    return list(map(sanitize_string, strings))

### Setup the Agents

In [4]:
os.environ['OLLAMA_HOST']   = 'http://localhost:11434'
os.environ['no_proxy']      = 'localhost,127.0.0.1'

In [5]:
from dotenv import load_dotenv

load_dotenv()

True

In [6]:
config_list = [
    {
        "model": "llama-3.3-70b-versatile",
        "api_type": "groq",
        "price": [0, 0],
        "timeout": 1_200,
        "temperature": 0,
        "tags": [
            "llama3.3"
        ]
    }
]

In [45]:
# set to true to disable agents conversation on stdout
silent = True

In [46]:
executor = LocalCommandLineCodeExecutor(
    timeout=10,  # Timeout for each code execution in seconds.
    work_dir='./coding',  # Use the temporary directory to store the code files.
)

In [47]:
nl_generator = AssistantAgent(
    name="NLQuestionGenerator",
    system_message="""
        You are an SQL expert of joinable tables.
        You will take two joinable tables from a datalake, each containing five example entries for each column. 
        You are required to GENERATE a natural language question that necessitate joining these two tables. 
        DO NOT generate the answer.
        Report also the corresponding SQL code block.
        Be sure to use the correct column names in the SQL block, and put column names inside ``.
        Generate the natural language question. 
        DO NOT add any other info.
        Make sure that SQL is written in a way that always returns at least one result.
        Make sure that table names are inside ''.
    """,
    llm_config={
        'config_list': config_list, # filter_config(config_list, {'tag': ['llama3.3']}), 
        'cache_seed': None
    },
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    silent=silent
)

In [48]:
user_proxy = UserProxyAgent(
    name="User_proxy",
    system_message="A human admin. Execute code when needed",
    code_execution_config={
        "last_n_messages": 3,
        "executor": LocalCommandLineCodeExecutor(work_dir="groupchat"),
    },
    human_input_mode="NEVER",
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    max_consecutive_auto_reply=5,
    silent=silent
)

In [49]:
def check_termination(msg: Dict):
    if "tool_responses" not in msg:
        return False
    # json_str = msg["tool_responses"][0]["content"]
    content = msg["tool_responses"][0]["content"]

    # print(f'>>>>>>>>>>>> OCCHIO {json_str}')
    # obj = json.loads(json_str.replace('\'', '"'))
    # print(f'>>>>>>>>>>>> TUTTO BENE {obj}')
    # return "error" not in json_str or obj["error"] is None and obj["reward"] == 1
    return "error" not in content


sql_writer = AssistantAgent(
    "sql_writer",
    system_message="You are good at writing SQL queries. Always respond with a function call to execute_sql(). DO NOT write python code.",
    is_termination_msg=check_termination,
    llm_config={
        'config_list': config_list, 
        'cache_seed': None
    },
    silent=silent
)

In [50]:
import csv
import sqlite3
from typing import Annotated, Dict


@sql_writer.register_for_llm(description="Function for executing SQL query and returning a response")
@user_proxy.register_for_execution()
def execute_sql(
    llm_question        : Annotated[str, "Think about the corresponding natural language question to SQL."],
    human_like_question : Annotated[str, "Convert question without using technical or specific column names. \
                                          Instead, replace them with more relatable and descriptive terms to make the question feel intuitive and conversational."],
    reflection          : Annotated[str, "Think about what to do"],
    sql                 : Annotated[str, "SQL query"], 
    table1              : Annotated[str, "Name of the first table"], 
    table2              : Annotated[str, "Name of the second table"]
) -> Annotated[Dict[str, str], "Dictionary with keys 'result' and 'error'"]:
        connection = None
        error = None
        result = None
        
        try:
            # Connect to the SQLite database
            connection = sqlite3.connect('tmp.db')
            cursor = connection.cursor()
            
            # Execute the SQL query
            cursor.execute(sql)
            # the fetchall could give troubles with large results set
            # result = cursor.fetchall()
            
            result = cursor.fetchmany(10)
            # Commit changes if the query modifies the database
            # (This should not happens, the queries are just SELECT)
            # connection.commit()
            
        except sqlite3.Error as e:
            error = str(e)
        
        finally:
            if connection:
                connection.close()
        
        if error:
            return {
                "error": error,
                "wrong_result": result if result else "No result",
            }
        
        
        elif len(result) == 0:
            return {
                "error":  'Empty result',
                "result": "No result",
            }
            
        else:
            # save results to csv
            file_exists = os.path.isfile(RESULTS_PATH)

            with open(RESULTS_PATH, 'a', newline='') as csvfile:
                csv_writer = csv.writer(csvfile)
                if not file_exists:
                    csv_writer.writerow(['llm_question', 'human_like_question', 'sql', 'table1', 'table2'])  # Write header
            
                csv_writer.writerow([llm_question.strip('"'), human_like_question.strip('"'), sql, table1, table2])

            return {"result": result}

In [51]:
sql_rewriter = AssistantAgent(
    "rewriter",
    system_message="Given an SQL query and an error try to modify the sql to avoid the error. Write only the new sql. DO NOT write python code.",
    is_termination_msg=check_termination,
    llm_config={
        'config_list': config_list,
        'cache_seed': None
    },
    silent=silent
)

In [52]:
groupchat = GroupChat(
    agents=[sql_writer, user_proxy, sql_rewriter], 
    messages=[], 
    max_round=30, 
    speaker_selection_method="round_robin"
)

manager = GroupChatManager(
    groupchat=groupchat, 
    llm_config={
        'config_list': config_list,
        'cache_seed': None
    }, 
    system_message="When the task is completed say TERMINATE",
    silent=silent
)

### Generate the Questions

In [53]:
with open(CLUSTERS_PATH, 'r') as fr:
    clusters = json.load(fr)

clusters = clusters['clusters']

In [54]:
# take only small clusters, for example those with <=N tables inside
max_cluster_size = 4
small_clusters = list(filter(lambda d: len(d['cluster']) <= max_cluster_size, clusters))
print(f'Number of clusters with at most {max_cluster_size}: {len(small_clusters)}')

Number of clusters with at most 4: 16

In [55]:
# define a function to read the tables directly from the .zip file
import zipfile

def read_table(table_id):
    with zipfile.ZipFile(DATASET_PATH, 'r') as zip_tables:
        with zip_tables.open(f'datasets_{OPENDS_NAME}/{table_id}', 'r') as table_file:
            try:
                df = pd.read_csv(table_file, on_bad_lines='skip')
                df.columns = sanitize_all_strings(df.columns)
                for attribute in df.columns:
                    df[attribute] = df[attribute].apply(sanitize_string)
                return df
            except Exception as e:
                return f'Error on reading table {table_id}: {e}'

In [56]:
# function calling example
table_id = small_clusters[0]['cluster'][0]
read_table(table_id)

,Ref_Date,GEOGRAPHY,CHARACTERISTICS,EDUCATIONLEVEL,SEX,AGEGROUP,Value
0,1990,Canada,"Population_(x_1,000)","Total,_all_education_levels",Both_sexes,15_years_and_over,21214_7
1,1991,Canada,"Population_(x_1,000)","Total,_all_education_levels",Both_sexes,15_years_and_over,21533_3
2,1992,Canada,"Population_(x_1,000)","Total,_all_education_levels",Both_sexes,15_years_and_over,21820_2
3,1993,Canada,"Population_(x_1,000)","Total,_all_education_levels",Both_sexes,15_years_and_over,22092_9
4,1994,Canada,"Population_(x_1,000)","Total,_all_education_levels",Both_sexes,15_years_and_over,22367_7
...,...,...,...,...,...,...,...
36445,2010,Alberta,Employment_rate_(rate),Above_bachelor's_degree,Females,65_years_and_over,x
36446,2011,Alberta,Employment_rate_(rate),Above_bachelor's_degree,Females,65_years_and_over,30_3
36447,2012,Alberta,Employment_rate_(rate),Above_bachelor's_degree,Females,65_years_and_over,27_4
36448,2013,Alberta,Employment_rate_(rate),Above_bachelor's_degree,Females,65_years_and_over,25_4
36449,2014,Alberta,Employment_rate_(rate),Above_bachelor's_degree,Females,65_years_and_over,33_8

In [57]:
gt = pd.read_csv(GT_PATH)
gt

                      query_table              candidate_table
0     CAN_CSV0000000000024893.csv  CAN_CSV0000000000020982.csv
1     CAN_CSV0000000000019383.csv  CAN_CSV0000000000002092.csv
2     CAN_CSV0000000000016797.csv  CAN_CSV0000000000011318.csv
3     CAN_CSV0000000000005930.csv  CAN_CSV0000000000001161.csv
4     CAN_CSV0000000000004711.csv  CAN_CSV0000000000004697.csv
...                           ...                          ...
3315  CAN_CSV0000000000013788.csv  CAN_CSV0000000000001071.csv
3316  CAN_CSV0000000000013788.csv  CAN_CSV0000000000000660.csv
3317  CAN_CSV0000000000013788.csv  CAN_CSV0000000000013712.csv
3318  CAN_CSV0000000000013788.csv  CAN_CSV0000000000000857.csv
3319  CAN_CSV0000000000013788.csv  CAN_CSV0000000000000701.csv

[3320 rows x 2 columns]

In [58]:
from sqlalchemy import Integer, String, Float, Boolean, DateTime

def map_dtype(dtype):
    if pd.api.types.is_integer_dtype(dtype):
        return Integer
    elif pd.api.types.is_float_dtype(dtype):
        return Float
    elif pd.api.types.is_bool_dtype(dtype):
        return Boolean
    elif pd.api.types.is_datetime64_any_dtype(dtype):
        return DateTime
    elif pd.api.types.is_string_dtype(dtype):
        return String
    else:
        raise ValueError(f"Unsupported dtype: {dtype}")

In [59]:
def import_csv_to_sqlite(df, table_name, db_connection):
    df.to_sql(table_name, db_connection, if_exists='replace', index=False)

In [60]:
from groq import BadRequestError
from sqlalchemy import MetaData, Table, Column, create_engine
from sqlalchemy.schema import CreateTable

import autogen
from tqdm import tqdm

if not os.path.isdir(REPR_ROWS_DIR_PATH):
    os.makedirs(REPR_ROWS_DIR_PATH)

# setup the SQLAlchemy engine
engine = create_engine('sqlite:///tmp.db')
metadata = MetaData()
conn = engine.connect()

old = []
tab = gt.drop_duplicates(subset=['query_table', 'candidate_table']).reset_index()

# Start logging with logger_type and the filename to log to
# logging_session_id = autogen.runtime_logging.start(logger_type="file", config={"filename": "runtime.log"})
# print("Logging session ID: " + str(logging_session_id))

for idx, row in tqdm(tab.iterrows(), total=tab.shape[0]):
    print(f'############ {idx} / {tab.shape[0]} ############')
    table1_id = tab[['query_table']].iloc[idx].values[0]
    table2_id = tab[["candidate_table"]].iloc[idx].values[0]

    # Load the representation of both tables 1 and 2 if the 
    # relative CSV files already exist, otherwise read the original
    # tables and sample few rows from them. Then, store the 
    # created snapshot
    if not os.path.exists(f'{REPR_ROWS_DIR_PATH}/{table1_id}'):
        table1 = read_table(table1_id)
        sample1 = table1.sample(N_REPRESENTATIVE_ROWS)
        sample1.to_csv(f'{REPR_ROWS_DIR_PATH}/{table1_id}', index=False)
        import_csv_to_sqlite(table1, table1_id.removesuffix('.csv'), conn)
    else:
        sample1 = pd.read_csv(f'{REPR_ROWS_DIR_PATH}/{table1_id}')
    
    if not os.path.exists(f'{REPR_ROWS_DIR_PATH}/{table2_id}'):
        table2 = read_table(table1_id)
        sample2 = table2.sample(N_REPRESENTATIVE_ROWS)
        sample2.to_csv(f'{REPR_ROWS_DIR_PATH}/{table2_id}', index=False)
        import_csv_to_sqlite(table2, table2_id.removesuffix('.csv'), conn)
    else:
        sample2 = pd.read_csv(f'{REPR_ROWS_DIR_PATH}/{table2_id}')

    # Now the '.csv' suffix is no longer needed
    table1_id = table1_id.removesuffix('.csv')
    table2_id = table2_id.removesuffix('.csv')

    # Create a table declaration for the two tables
    t1_sql = Table(table1_id, metadata, *[Column(col_name, map_dtype(dtype)) for col_name, dtype in sample1.dtypes.items()])
    t2_sql = Table(table2_id, metadata, *[Column(col_name, map_dtype(dtype)) for col_name, dtype in sample2.dtypes.items()])
    
    # Create the statements for CREATE TABLE
    s1 = str(CreateTable(t1_sql).compile(engine))
    s2 = str(CreateTable(t2_sql).compile(engine))
    
    # Try to generate the questions
    for i in range(N_QUERIES_PER_PAIR):
        try:
            resuts=manager.initiate_chat(
            nl_generator,
            message=f"""
                These are two joinable tables:
                ##########################
                Table '{table1_id}': {s1} 

                Example:
                {sample1}
                ##########################
                Table '{table2_id}': {s2} 

                Example:
                {sample2}
                ##########################
                
                make sure to be a lot different from old question:
                {old}
                You are required to GENERATE a natural language question that necessitate joining these two tables. 
                Do not generate the answer.
                Report also the corresponding SQL code block.
                Rembember that table 1 is {table1_id} and table 2 name is {table2_id}.
                Be sure to use the correct column and table names in the SQL block, and put column names inside ''.
                Generate the natural language question and do not add any other info.
                Do not translate columns to english if they are in french, use names as it is.
                Make sure that table names are inside ''.
                If the tables in your opinion do not do join say TERMINATE.
                WRITE ONLY NATURAL QUESTION:
            """,
            silent=silent
            )
        except BadRequestError:
            print('Fake bad tool call')
        
        gt = pd.read_csv(RESULTS_PATH)
        old = list(gt[(gt['table1'] == table1_id) & (gt['table2'] == table2_id)]['sql'].values)

# autogen.runtime_logging.stop()
conn.close()

  0%|          | 0/3320 [00:00<?, ?it/s]

############ 0 / 3320 ############

  0%|          | 0/3320 [00:00<?, ?it/s]

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01jf797321fmvbmd3xq4s9e3yq` service tier `on_demand` on : Limit 100000, Used 99925, Requested 1987. Please try again in 27m31.715s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': '', 'code': 'rate_limit_exceeded'}}

# ISSUE: How we can actually generate a benchmark? The mapping LakeBench-GroundTruth - OpenDataPortalsIDs is missing

What if we generate for each query some random word, query the API, then take pairs of tables and if these are joinable use them as potential ground truth to define new queries?

In [98]:
import requests

In [101]:
api_base_url = 'https://open.canada.ca/data/api/action'
# api_base_url = 'https://catalog.data.gov/api/3/action'

q = f'{api_base_url}/package_search?q=environment&rows=100'
# q = f'{api_base_url}/package_list'
# q = 'https://api.us.socrata.com/api/catalog/v1'
response = requests.get(q)

response.status_code

200

In [106]:
response.json()['result']['results'][0]['keywords']

{'fr': ['carte', 'carte demographique', 'qualité de vie'],
 'en': ['demographic maps', 'map', 'quality of life']}

In [80]:
for result in response.json()['result']['results']:
    # print('P >', result['title'])
    for resource in result['resources']:
        if resource['format'].upper() in {'CSV', 'ZIP'}:
            print('\tR >', result['title'], resource['id'], resource['name'], resource['description'])

	R > Electric Vehicle Population Data fa51be35-691f-45d2-9f3e-535877965e69 Comma Separated Values File
	R > Air Quality f3ed1638-92da-4f88-bb6b-7d3940514574 Comma Separated Values File
	R > Sugar-Sweetened Beverage Consumption in California Residents 327fe3fc-8ae2-471e-b059-0e036dc87df9 Sugar-Sweetened Beverage Consumption in California Residents, 2012/2013 (CSV) The mean servings/times sugar-sweetened beverages consumed daily by California residents. These data are from the 2013 California Dietary Practices Surveys (CDPS), 2012 California Teen Eating, Exercise and Nutrition Survey (CalTEENS), and 2013 California Children’s Healthy Eating and Exercise Practices Survey (CalCHEEPS). These surveys are now discontinued. Adults, adolescents, and children (with parental assistance) were asked about the sugar-sweetened beverages they drank over the previous 24 hour period. Child/Adolescent: Fruit and vegetable, beverage, and junk food consumption, along with physical activity, sedentary time, active transport, sport participation, school environment, home neighborhood environment, fruit and vegetable access and availability, household/family rules, weight status, school breakfast/lunch participation, attitudes, and beliefs. Adult: Fruit and vegetable, beverage, and junk food consumption, along with physical activity, sedentary time, worksite environment, school environment, home neighborhood environment, fruit and vegetable access and availability, household/family rules, weight status and weight loss practices, and food security. According to the Dietary Guidelines for Americans, 2010, sugar-sweetened beverages provide excess calories and few essential nutrients to the diet and should only be consumed when nutrient needs have been met and without exceeding daily calorie limits.
	R > Sugar-Sweetened Beverage Consumption in California Residents a11ca59b-5d21-4fcb-869c-04c7e930da05 All resource data sugar-sweetened-beverage-consumption-in-california-residents-2012-2013-753xhqs6.zip
	R > NYC Building Energy and Water Data Disclosure for Local Law 84 (2022-Present) bdfdc84e-8738-4ea2-a91f-ab841423e848 Comma Separated Values File
	R > Walkability Index 89b876c2-934f-4d06-b895-6949edfcb53c Download The URL providing direct access to the downloadable dataset.
	R > Walkability Index 356986ec-b9ab-4fdf-8838-7262a08502e3 API The endpoint of a web service to access the dataset (REST endpoint, WMS GetCapabilities URL, or a SOAP WSDL endpoint).
	R > Electric Vehicle Charging Stations 7930839c-420a-446a-8d84-43fac6717c19 Comma Separated Values File
	R > Biodiversity by County - Distribution of Animals, Plants and Natural Communities 3f1f3935-8eb1-4a52-8cde-3c65679eee70 Comma Separated Values File
	R > Fruit and Vegetable Consumption in California Residents, 2012/2013 38e34cfc-d3e2-482d-803f-c00fd13d8874 Fruit and Vegetable Consumption in California Residents, 2012/2013 (CSV) Percentage of California residents who consumed five or more servings of fruits and vegetables a day. These data are from the 2013 California Dietary Practices Surveys (CDPS), 2012 California Teen Eating, Exercise and Nutrition Survey (CalTEENS), and 2013 California Children’s Healthy Eating and Exercise Practices Survey (CalCHEEPS). These surveys have been discontinued. Adults, adolescents, and children (with parental assistance) were asked about the serving sizes and types of fruits and vegetables they ate over the previous 24 hour period. Child/Adolescent: Fruit and vegetable, beverage, and junk food consumption, along with physical activity, sedentary time, active transport, sport participation, school environment, home neighborhood environment, fruit and vegetable access and availability, household/family rules, weight status, school breakfast/lunch participation, attitudes, and beliefs. Adult: Fruit and vegetable, beverage, and junk food consumption, along with physical activity, sedentary time, worksite environment, school environment, home neighborhood environment, fruit and vegetable access and availability, household/family rules, weight status and weight loss practices, and food security.
	R > Fruit and Vegetable Consumption in California Residents, 2012/2013 65157e36-78de-4154-b23f-e22bcf161a1e All resource data fruit-and-vegetable-consumption-in-california-residents-2012-2013-oll8md03.zip
	R > Clean Air Status and Trends Network (CASTNET): Ozone cac5d596-bb18-484c-b3da-7ecf89340a37 Comma Separated Values File
	R > Freight Analysis Framework 3b4709cc-7906-4de9-bd99-bb5e95e7f0cd Regional Data base for 2007 with forecasts through 2040 faf3_5.zip
	R > Educational Attainment 04af3bc5-4184-4329-9e5a-88e167d44ee8 All resource data educational-attainment-mldflt.zip
	R > Electric Vehicle Title and Registration Activity d045f505-3b06-4471-953c-1a754c295a9c Comma Separated Values File
	R > Chicago Public Schools - Progress Report Cards (2011-2012) 13da9f73-fe70-41af-83a2-cbefedd92d03 Comma Separated Values File
	R > National Greenhouse Gas Emission Inventory 4f073b5a-74e6-48aa-9ac4-4df722c1062c Comma Separated Values File
	R > Current Invasive Plants (Feature Layer) a1ee148e-7e8e-4e02-a042-87ad3053ca14 CSV
	R > Current Invasive Plants (Feature Layer) ce2737cc-4210-4449-9a09-5184fbfaad1d Shapefile
	R > Average Residential Retail Propane Prices by Region: Beginning 1997 94570829-47cb-476b-b3a6-9d8a17de5d7b Comma Separated Values File
	R > Provider of Services File - Hospital & Non-Hospital Facilities 9a43975c-4873-441a-a1f5-0ab93dedd7fb Provider of Services File - Hospital & Non-Hospital Facilities : 2024-12-02 PQWB.POSQ.OTHER.DATA.DEC24.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities b76f9d93-91c2-4b34-a89b-995d5980e6a1 Provider of Services File - Hospital & Non-Hospital Facilities : 2024-09-01 other_data_Q3%202024.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities d3d631d8-6aee-4076-ad86-92e6d398f3c6 Provider of Services File - Hospital & Non-Hospital Facilities : 2024-04-01 other_data_Q2%202024.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 0221ba5f-7966-4e87-9236-9685b1ff09f3 Provider of Services File - Hospital & Non-Hospital Facilities : 2024-03-31 other_data_mar24.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 91ca1351-fe2d-46a3-a60a-1a3fd3d9497e Provider of Services File - Hospital & Non-Hospital Facilities : 2023-12-31 other_data_yr23.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities d5a122f9-61ee-40af-a925-a8f8be845faf Provider of Services File - Hospital & Non-Hospital Facilities : 2023-09-01 POS_OTHER_Sep23.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities d46413e2-68b1-4eec-bb25-5a18e5fa65ee Provider of Services File - Hospital & Non-Hospital Facilities : 2023-06-01 POS_OTHER_JUN23.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 8df914e9-6725-4b8d-955d-e16890db3541 Provider of Services File - Hospital & Non-Hospital Facilities : 2023-03-31 POS_OTHER_MAR23.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 6b09e55a-1ce4-4434-b24c-41a513e2227f Provider of Services File - Hospital & Non-Hospital Facilities : 2022-12-31 POS_OTHER_DEC22.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities c87617c9-9f6c-4c56-b2b2-3fc415b94751 Provider of Services File - Hospital & Non-Hospital Facilities : 2022-09-30 OTHER_Q3Y22.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 029fa24e-bbc2-4d67-8346-151f894bcb25 Provider of Services File - Hospital & Non-Hospital Facilities : 2022-06-30 OTHER_Q2Y22.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 7131f3a6-ba65-4e27-879e-7aab07086814 Provider of Services File - Hospital & Non-Hospital Facilities : 2022-03-31 POS_OTHER_MAR22_0.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 6e3c0f53-4274-4c3e-8e80-39a35aa9b846 Provider of Services File - Hospital & Non-Hospital Facilities : 2021-12-31 POS_OTHER_DEC21.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 6cd8c044-cf92-4ff6-8aea-e49417f87f72 Provider of Services File - Hospital & Non-Hospital Facilities : 2021-09-30 POS_OTHER_SEP21.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 6238b40d-131f-4187-900c-92de3bcc70b4 Provider of Services File - Hospital & Non-Hospital Facilities : 2021-06-30 provider_of_services_file_hospital_non_hospital_facilities_2021_06_30.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 27ff6ca2-fde4-4fdb-8048-402fbec96ba2 Provider of Services File - Hospital & Non-Hospital Facilities : 2021-03-31 provider_of_services_file_-_other_-_march_2021-2.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 37679058-2f66-42d3-84b6-0bea0dd94adc Provider of Services File - Hospital & Non-Hospital Facilities : 2020-12-30 pos_other_Dec20.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities e2aa4dc6-4a44-408f-a148-e8ba3a64c1ef Provider of Services File - Hospital & Non-Hospital Facilities : 2020-09-30 pos_other_sep20.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 747dc0fc-c471-4db9-afff-6809b43d4d12 Provider of Services File - Hospital & Non-Hospital Facilities : 2020-06-30 Provider_of_Services_File_-_OTHER_-_June_2020.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities c615395d-695f-428e-b548-1dd236ea3493 Provider of Services File - Hospital & Non-Hospital Facilities : 2020-03-31 POS_OTHER_MAR20.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities fd3875ae-a78a-4840-bb2a-15fd2c0e3c57 Provider of Services File - Hospital & Non-Hospital Facilities : 2019-12-31 POS_OTHER_DEC19.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities a61e05be-2fb1-4e02-91c6-2a47d360fe79 Provider of Services File - Hospital & Non-Hospital Facilities : 2019-09-30 POS_OTHER_SEP19.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 34787f21-4a84-478b-a196-159307c50d3c Provider of Services File - Hospital & Non-Hospital Facilities : 2019-06-30 POS_OTHER_JUN19.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities d25444c0-b1c5-4aa7-85a7-caa65e54a1c7 Provider of Services File - Hospital & Non-Hospital Facilities : 2019-03-31 POS_OTHER_MAR19.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 457c4a0d-7572-4b49-aeed-7803d926286d Provider of Services File - Hospital & Non-Hospital Facilities : 2018-12-31 POS_OTHER_DEC18.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities b6c8fb38-64ea-4fe5-b475-76f3ea719564 Provider of Services File - Hospital & Non-Hospital Facilities : 2017-12-31 pos_other_dec17.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 641a62d8-9161-4402-879d-14395a0c1021 Provider of Services File - Hospital & Non-Hospital Facilities : 2016-12-31 POS_OTHER_DEC16.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities a4262061-6c36-458c-98af-4899937b4a08 Provider of Services File - Hospital & Non-Hospital Facilities : 2015-12-31 POS_OTHER_DEC15.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities 0fa6457a-ecc3-4189-a80a-1db3da2d3018 Provider of Services File - Hospital & Non-Hospital Facilities : 2014-12-31 POS_OTHER_DEC14.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities bcaaa1f3-3d75-46eb-8c41-b128b70d2a90 Provider of Services File - Hospital & Non-Hospital Facilities : 2013-12-31 POS_OTHER_DEC13.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities bde5b479-a00a-4d57-a1d1-188abcbb4d6d Provider of Services File - Hospital & Non-Hospital Facilities : 2012-12-31 POS_OTHER_DEC12_0.csv
	R > Provider of Services File - Hospital & Non-Hospital Facilities de058d63-e961-48f1-b820-6190ad812d52 Provider of Services File - Hospital & Non-Hospital Facilities : 2011-12-31 POS_OTHER_DEC11.csv
	R > Bulk Storage Facilities in New York State 4e18e696-cd05-4699-b49e-f33f84c0daef Comma Separated Values File
	R > Power Outages - Zipcode e692cf9e-691b-4aa2-a0db-6d6c0bb921c5 Comma Separated Values File
	R > TSCA Inventory f03d84a7-7ef9-498c-a643-28113495902b Comma Separated Values File
	R > Food Waste Recycling Impact 0638fe53-8fc9-46f6-8c6d-d9def0e2d4f9 Comma Separated Values File
	R > Greenhouse Gas Emissions ec1b00d3-2113-40b9-ba15-b0649a539ec2 Comma Separated Values File
	R > NYSERDA New York Offshore Wind Supply Chain Dataset 0ce0dbce-27a7-4ff5-904f-17fe9569151b Comma Separated Values File
	R > 2018 Central Park Squirrel Census - Hectare Data 29c145b2-cd86-4c66-825a-c61b02698305 Comma Separated Values File
	R > Safety Pilot Model Deployment Data a2d6f893-a3b4-4597-a8d0-ba4a49aaa05e BrakeByte1Events BrakeByte1Events.csv.zip
	R > Safety Pilot Model Deployment Data 7323bc35-856d-417a-969e-744b93d89ccc BrakeByte2Events BrakeByte2Events.csv.zip
	R > Safety Pilot Model Deployment Data 322204da-9aa9-4139-b44f-93380019a875 BSMEventFlag BsmEventFlag.csv.zip
	R > Safety Pilot Model Deployment Data 637cbd8d-e202-4e61-8bad-aaa48e6502de BSMMd BsmMd.csv.zip
	R > Safety Pilot Model Deployment Data 4029f4ea-43f6-4b2d-8a33-1c2b690ba416 BSMP1 BsmP1.csv.zip
	R > Safety Pilot Model Deployment Data 4f9562e6-884e-4663-9442-6995568d0011 BSMP1Summary BsmP1Summary.csv.zip
	R > Safety Pilot Model Deployment Data 4e38093b-658f-477f-ad73-a7dab7db2727 DataDas DataDas.csv.zip
	R > Safety Pilot Model Deployment Data 6fa33ec2-846e-4109-83e5-8608e1ea0c76 DataFrontTargets DataFrontTargets.csv.zip
	R > Safety Pilot Model Deployment Data 6720765d-cdca-47f6-94dc-276bd29d1824 DataGPSDas DataGpsDas.csv.zip
	R > Safety Pilot Model Deployment Data 225b8e9a-3368-4e49-bddf-648591ad24ed DataLane DataLane.csv.zip
	R > Safety Pilot Model Deployment Data 48616686-f953-46ae-b109-85184dfaa7cc DataRv DataRv.csv.zip
	R > Safety Pilot Model Deployment Data 865d7ca1-8649-4d25-9b07-03fb9dd5d5b5 DataWsu DataWsu.csv.zip
	R > Safety Pilot Model Deployment Data 2115810d-c921-45ae-aa98-58b619d9eda5 DataWsuSummary DataWsuSummary.csv.zip
	R > Safety Pilot Model Deployment Data cd1b0ba2-af1b-43e6-bd15-1708592b36f9 ExteriorLightsEvents ExteriorLightsEvents.csv.zip
	R > Safety Pilot Model Deployment Data 818b3b20-236f-4a24-809d-bbc055dadecd Geometry Geometry.csv.zip
	R > Safety Pilot Model Deployment Data 1e57a68b-acfc-4f00-bf65-06c072da38bb HV_Primary HV_Primary.csv.zip
	R > Safety Pilot Model Deployment Data 1282d642-0041-4ace-98d9-3fb15316c57d HV_Radar HV_Radar.csv.zip
	R > Safety Pilot Model Deployment Data 50999d01-5ba4-4d0e-b59e-34eb10ec6cda Lane Lane.csv.zip
	R > Safety Pilot Model Deployment Data 04d609d8-8d07-4da6-8055-5e032bd9873a LaneNode LaneNode.csv.zip
	R > Safety Pilot Model Deployment Data 6a730872-334a-4010-a3b8-0de71305b39d MAP MAP.csv.zip
	R > Safety Pilot Model Deployment Data 540812c7-dc59-4143-b203-988643848891 NetworkAADTCount NetworkAADTCount.csv.zip
	R > Safety Pilot Model Deployment Data c3e69b26-9b23-41c5-a6bd-7370b6f02576 NetworkTrafficCount NetworkTrafficCount.csv.zip
	R > Safety Pilot Model Deployment Data ac3749b0-ed7f-4992-aea6-84cd8c100375 Packet Packet.csv.zip
	R > Safety Pilot Model Deployment Data 97648f6f-07b3-4680-943e-7c90a8301182 PCAPFile PCAPFile.csv.zip
	R > Safety Pilot Model Deployment Data 27c90ee4-7023-42a7-8e0c-eabe81814a04 PosAccurByte1Events PosAccurByte1Events.csv.zip
	R > Safety Pilot Model Deployment Data 0afffc28-3661-44b7-8767-fc317fb55bd2 PosAccurByte2Events PosAccurByte2Events.csv.zip
	R > Safety Pilot Model Deployment Data 45cc9835-73ad-430b-b100-2dbbf651d012 PosAccurByte3Events PosAccurByte3Events.csv.zip
	R > Safety Pilot Model Deployment Data 49e0eb3d-b16a-49a3-bd3d-07806f2bd234 PosAccurByte4Events PosAccurByte4Events.csv.zip
	R > Safety Pilot Model Deployment Data 7cf3af8f-9ab9-4830-8866-ac91fe5710a9 RSE_BSM RSE_BSM.csv.zip
	R > Safety Pilot Model Deployment Data cdaa54bc-e97e-4d7b-85aa-6761ac79dbaa RV_RX RV_RX.csv.zip
	R > Safety Pilot Model Deployment Data ac1d8f99-cf8c-488f-af7e-beec3a8f791b SPAT SPAT.csv.zip
	R > Safety Pilot Model Deployment Data 04fbbab1-f0f7-425e-8432-9d01f3f383e9 SPATMovement SPATMovement.csv.zip
	R > Safety Pilot Model Deployment Data fa30e9d2-37c9-4445-8b49-0c5834bc4623 SteerAngleEvents SteerAngleEvents.csv.zip
	R > Safety Pilot Model Deployment Data 0433ea9b-201e-4648-9518-0406d7fc5db4 ThrottlePositionEvents ThrottlePositionEvents.csv.zip
	R > Safety Pilot Model Deployment Data 8800fb30-6fbd-4597-a222-4b43727e94d2 TIM TIM.csv.zip
	R > Safety Pilot Model Deployment Data 4fc29804-c455-4291-907e-9c91a49c86f8 TIMRegion TimRegion.csv.zip
	R > Safety Pilot Model Deployment Data 36b19593-aa51-48ff-8ea7-d4a7b0862d3f TIMRegionNode TIMRegionNode.csv.zip
	R > Safety Pilot Model Deployment Data 21d600cf-2a12-4cef-9b70-c7f9def88d1d TIMRegionXref TIMRegionXref.csv.zip
	R > Safety Pilot Model Deployment Data 6f129cdc-c01c-4fee-98c6-0e6e3d7a9ac0 TransStateEvents TransStateEvents.csv.zip
	R > Safety Pilot Model Deployment Data 1bdccc41-e612-4fbf-9ba0-7f7010950de1 TripFact TripFact.csv.zip
	R > Safety Pilot Model Deployment Data 599d7fd6-9dd5-44ad-997e-97fbb322a707 Weather Weather.csv.zip
	R > Safety Pilot Model Deployment Data b3ac94a9-35f5-4375-a190-d2a62b8fe333 WiperStatusFrontEvents WiperStatusFrontEvents.csv.zip
	R > NPL Superfund Site Boundaries (EPA) 8f76ef6d-1e8f-4219-904e-973697b5b9f5 Zipped file geodatabase NPL_Boundaries.zip
	R > Forestry Tree Points 015d5eb5-f817-4793-a0b5-2efaaa890950 Comma Separated Values File
	R > 2018 Central Park Squirrel Census - Squirrel Data f8481d6e-98c9-40b6-a412-505d5e542823 Comma Separated Values File
	R > Clean Air Markets Program Data Application (CAMPD) 20a6d44e-d476-4a28-b122-f1c4a4978be5 Comma Separated Values File
	R > Smart Location Database 0a7b2b6a-6117-4fba-8e90-31d79b9cf55b Zip File SmartLocationDatabaseV3.zip
	R > Smart Location Database c2f990b7-0771-4dd6-a3c7-3d70e3996487 Comma Separated Values File EPA_SmartLocationDatabase_V3_Jan_2021_Final.csv
	R > Characterization Factors for Construction Material EPD Indicators (ISO21930-LCIA-US) v0.1 f9102732-5d33-4e98-9bfb-508ad1f22790 Zip File ISO21930-LCIA-USv0.1_noflows_json-ld.zip
	R > Characterization Factors for Construction Material EPD Indicators (ISO21930-LCIA-US) v0.1 8280b516-83bb-4e64-b492-4b21aa06c794 Zip File ISO21930-LCIA-USv0.1_wprefflows_json-ld.zip
	R > Event-correlated Outage Dataset in America b74446fb-892b-4841-92df-47d6a3ef1036 Outage Dataset.zip Archive of the Outage dataset containing aggregated outage data, merged outage data, and event-correlated data. For more information on the data included and instructions see the "Data Guidelines" resource.
	R > Report on U.S. Methane Emissions 1990-2020: Inventories, Projections, and Opportunities for Reductions: 2001 Updated emission and cost estimates e2250a5e-7ddf-4f26-a574-44e7dd3690e0 Comma Separated Values File
	R > Air Quality Annual Summary 90163dbc-c7e9-476f-a9f8-f363f5a535bd Comma Separated Values File
	R > Air Emissions/IGD: EF_ICIS_AIR ef126bc4-5b01-4cca-b9df-d3b401a84e68 Comma Separated Values File EF_ICIS_AIR.csv
	R > New York City Climate Projections: Temperature and Precipitation fdd83034-542d-49b8-b286-ffc701e06b96 Comma Separated Values File
	R > NUOnet (Nutrient Use and Outcome Network) database 4558377c-b9f5-485d-8aa6-414d7bcf1751 DET_NATRES_NUO.zip
	R > NUOnet (Nutrient Use and Outcome Network) database 797c5676-2e43-49e0-b434-7e66c4d43a12 GRACEnet-NUOnet_DD.csv
	R > Energy and Water Data Disclosure for Local Law 84 2022 (Data for Calendar Year 2021) faeb2319-04a1-4f01-b97c-681c2d2d0cc1 Comma Separated Values File
	R > Toxic Substances Control Act (TSCA) 8(e) Notices and FYI Submissions 69fa9320-6682-4502-a491-7fa07fc891d5 Comma Separated Values File
	R > Clean Air Status and Trends Network (CASTNET) Download Data Module 951f085d-025b-493a-aa26-df68b71fcce0 Comma Separated Values File clearsession.do
	R > Local Weather Archive 70f03146-c910-4baf-a1e3-9cc92bc7d9bb Comma Separated Values File

In [29]:
response.json()['result']['results'][0]['resources']

[{'cache_last_updated': None,
  'cache_url': None,
  'created': '2017-01-26T12:46:50.568141',
  'data_quality': [],
  'datastore_active': False,
  'description': '',
  'format': 'JP2',
  'hash': '',
  'id': '8d185c97-c9b0-4ff4-ae89-9597edbce52e',
  'language': ['en', 'fr'],
  'last_modified': None,
  'metadata_modified': '2017-01-26T12:46:50.568141',
  'mimetype': None,
  'mimetype_inner': None,
  'name': 'Download the English JP2 File through HTTP',
  'name_translated': {'fr': 'Télécharger le fichier en format JPEG2000 Anglais via HTTP',
   'en': 'Download the English JP2 File through HTTP'},
  'package_id': 'dea5e91e-8893-11e0-8a89-6cf049291510',
  'position': 0,
  'resource_type': 'dataset',
  'state': 'active',
  'url': 'https://ftp.geogratis.gc.ca/pub/nrcan_rncan/raster/atlas_6_ed/eng/6462_the_37th_federal_election_2000.jp2',
  'url_type': None},
 {'cache_last_updated': None,
  'cache_url': None,
  'created': '2017-01-26T12:46:50.568178',
  'data_quality': [],
  'datastore_active': False,
  'description': '',
  'format': 'ZIP',
  'hash': '',
  'id': '1ddebe00-e4d0-44ad-bf38-b57ca5432284',
  'language': ['en', 'fr'],
  'last_modified': None,
  'metadata_modified': '2017-01-26T12:46:50.568178',
  'mimetype': None,
  'mimetype_inner': None,
  'name': 'Download the English ZIP (PDF,JPG) file through HTTP',
  'name_translated': {'fr': 'Télécharger le fichier en format ZIP (PDF, JPG) Anglais via HTTP',
   'en': 'Download the English ZIP (PDF,JPG) file through HTTP'},
  'package_id': 'dea5e91e-8893-11e0-8a89-6cf049291510',
  'position': 1,
  'resource_type': 'dataset',
  'state': 'active',
  'url': 'https://ftp.geogratis.gc.ca/pub/nrcan_rncan/raster/atlas_6_ed/eng/6462_the_37th_federal_election_2000.zip',
  'url_type': None},
 {'cache_last_updated': None,
  'cache_url': None,
  'created': '2017-01-26T12:46:50.568191',
  'data_quality': [],
  'datastore_active': False,
  'description': '',
  'format': 'other',
  'hash': '',
  'id': '2b4a19ea-2718-49c8-a5d1-49330c971b36',
  'language': ['en', 'fr'],
  'last_modified': None,
  'metadata_modified': '2017-01-26T12:46:50.568191',
  'mimetype': None,
  'mimetype_inner': None,
  'name': 'Download the French JP2 File through HTTP',
  'name_translated': {'fr': 'Télécharger le fichier en format JP2 français via HTTP',
   'en': 'Download the French JP2 File through HTTP'},
  'package_id': 'dea5e91e-8893-11e0-8a89-6cf049291510',
  'position': 2,
  'resource_type': 'dataset',
  'state': 'active',
  'url': 'https://ftp.geogratis.gc.ca/pub/nrcan_rncan/raster/atlas_6_ed/fra/6462_la_37e_election_federale_2000.jp2',
  'url_type': None},
 {'cache_last_updated': None,
  'cache_url': None,
  'created': '2017-01-26T12:46:50.568204',
  'data_quality': [],
  'datastore_active': False,
  'description': '',
  'format': 'ZIP',
  'hash': '',
  'id': '10a8877e-3e70-42eb-be92-022c59096cf8',
  'language': ['en', 'fr'],
  'last_modified': None,
  'metadata_modified': '2017-01-26T12:46:50.568204',
  'mimetype': None,
  'mimetype_inner': None,
  'name': 'Download the French ZIP (PDF, JPG) File through HTTP',
  'name_translated': {'fr': 'Télécharger le fichier en format ZIP (PDF,JPG) français via HTTP',
   'en': 'Download the French ZIP (PDF, JPG) File through HTTP'},
  'package_id': 'dea5e91e-8893-11e0-8a89-6cf049291510',
  'position': 3,
  'resource_type': 'dataset',
  'state': 'active',
  'url': 'https://ftp.geogratis.gc.ca/pub/nrcan_rncan/raster/atlas_6_ed/fra/6462_la_37e_election_federale_2000.zip',
  'url_type': None}]