In [32]:
import zipfile
from itertools import chain
from collections import defaultdict

import pandas as pd

In [33]:
data_path           = '../data'
join_lb_gt_path     = f'{data_path}/lakebench_gt/opendata_join_ground_truth.csv'
union_lb_gt_path    = f'{data_path}/lakebench_gt/opendata_union_ground_truth.csv'

## How many perfect duplicated tables there are into each dataset?

Some tables seems to be actually a duplicate

In [ ]:
from tqdm import tqdm
import concurrent.futures

def process_country(country, data_path):
    country_hash_counts = defaultdict(int)
    with zipfile.ZipFile(f'{data_path}/datasets/datasets_{country}.zip') as z:
        for fname in tqdm(z.namelist(), leave=False):
            with z.open(f'{fname}') as fr:
                country_hash_counts[hash(fr.read())] += 1
    return country, country_hash_counts

countries = ['SG', 'USA', 'UK', 'CAN']

hash_counts = defaultdict(lambda: defaultdict(int))
def f(country):
    return process_country(country, data_path)

with concurrent.futures.ProcessPoolExecutor() as executor:
    results = executor.map(f, countries)

    for country, country_hash_counts in results:
        hash_counts[country].update(country_hash_counts)

defaultdict(<function <lambda> at 0x7f3b1129d080>, {'SG': defaultdict(<class 'int'>, {0: 1, -4674875556263080793: 1, -7634741486389042413: 1, 4263132111951713335: 1, -6302499288434989255: 1, 4324209699969771385: 1, -6435633116165740761: 2, -651822304665593260: 2, 1279420588976299611: 2, 3736502434966160822: 1, 4396213993875151283: 1, 2475886754674689859: 1, -5352036375098766840: 1, 5324245222568634465: 1, -2028616219097356053: 1, 5359489003082805105: 1, -210506810777125347: 1, -1971028898206908090: 1, 5037293001939319807: 1, -6047190395788212743: 1, 7668045894178019434: 1, 6699206777213831161: 1, -456163232713596945: 1, 8285159829220846430: 1, -2324800779446475024: 1, 6509605649039986618: 1, 19750657508789322: 1, 3731304696159723041: 1, -4305375258353556421: 1, -8623446016486027029: 1, 5883705141412307463: 1, -7745546256398028881: 1, 7823516721347420741: 1, -4004241964684670027: 1, -4647055146104747873: 1, 6171706816502946508: 1, 5748786110265944514: 1, 3032368955369073361: 1, 8391614412561017678: 1, -5432326282562217515: 1, 2628196837896359264: 1, 7542894178074572419: 1, -7565932166301186675: 1, 2480508673637895379: 1, 8724769633611404985: 3, 9047718317184353304: 1, 459875686770610857: 1, -355671298863088718: 1, 5208864999872149792: 1, -663286433009204140: 1, -1866370633204517204: 1, -5708221581728772198: 1, -3622498569317398989: 1, -132964428489981151: 1, -8375240667396871130: 1, 8415824906538584491: 1, 6494555673501494811: 1, 5755588467208535190: 1, 9002688436869713654: 2, -5616993115817304673: 1, -2947768582064333055: 1, 9187525497712393540: 1, 4237689045586318803: 1, 455264820152499777: 1, 522483209250343980: 1, -5552038254404688604: 1, -6633930956743474: 1, -1947044783285659155: 1, 6216247159662325549: 1, -7856409217459634240: 1, 6039353950123377481: 1, -8857758744810920639: 1, -5163692148399434050: 1, -4163150256318340352: 1, -137069590998203795: 1, 2047532255714771440: 1, 3336304670518196853: 1, -3878736247814594594: 1, 3805505971436772192: 1, 8495016676401528080: 1, -1706727457441934031: 1, -6737721404494934329: 1, -2649983276268770316: 1, 9026976155656702846: 1, 7666028068965629430: 1, 2860411853647600496: 1, 5304446840565741666: 1, -7261287339222580622: 1, 8286629696618598418: 1, -7715105884126526000: 1, -3786829771435763343: 1, 1563713047700328393: 1, 7346244633469250998: 1, -6149844895905391683: 1, 6950890885012990888: 1, 484144596672930012: 1, 4178116031783413549: 1, 5964022038158766569: 1, 5139876772318441752: 1, 7242658130240599729: 1, -8376920449434249998: 1, -777947703592399241: 1, -4104792034787067697: 1, -6334973774529902523: 1, 4712888526193226413: 1, 8735246098859991410: 1, 4906138843381404359: 1, 1916864682654790710: 1, 5245495314818657809: 1, 745995524643124730: 1, -1687148072153485576: 1, -3801216121450991935: 1, 4058718670452402104: 1, 6443454216380505177: 1, -7806137182372636992: 1, -2557400047758763194: 1, -2476719139279063877: 1, -4221932699345211337: 1, 6079333267713058373: 1, 855105356754336025: 1, -4997900676313906306: 1, -5288813985943955909: 1, -4174689630742271183: 1, -173526079006532602: 1, -4183809292003656802: 1, -5514259375791358245: 1, -4489933782849273187: 1, -4045914866358488315: 1, -313388869868060921: 1, 4674776201462085519: 1, 6566172979056447503: 1, -1966147609631256715: 1, 2302252078294043944: 1, 2484106758905131289: 1, 9138476324154265542: 1, -1835809011197121478: 1, 7818104197938445053: 1, -7891158853361376998: 1, -6650595837504049421: 1, 7015103652882042509: 1, 272344563304131440: 1, 8097135606623536752: 1, -1249649531544975780: 1, 7929369983129786813: 1, 7390299987506400462: 1, 2603035177694254518: 1, -1895369816410748666: 1, -6122140482004275975: 1, -926049676967932094: 1, -5029363507715061647: 1, -8198288896511910068: 1, 6839447945463446812: 1, 904614937798454225: 1, -1340774055645293722: 1, -2570945787759108702: 1, -2068402102685975896: 1, 81374063017263557: 1, -8454562430609892811: 1, -7277032233107290481: 1, -4573059157197463059: 1, -4054421443988144353: 1, 7059044764374549883: 1, 7177055948410718660: 1, 4765979313001417189: 1, -1883068220565692277: 1, -9218483505567245127: 1, 5000331896158935763: 1, -3895568629224147255: 1, -5045435336910256807: 1, -5438834771998421144: 1, -4091809209531287620: 1, -2260895833405697579: 1, -9068186257621712348: 2, -1708694929620214633: 1, 2895173640799698765: 1, 7097005807177931270: 1, 1213628979702012263: 1, 1016456865961896972: 1, -7899091129418432640: 1, -3642371347778292875: 1, -6785074693702708369: 1, 1544904103765769769: 1, 2795495985325815568: 1, 943507761492668475: 1, 7025780427484963402: 1, -1606016784191532892: 1, 5214521353381704731: 1, 3006118242769466270: 1, 8279821406789575123: 1, 6919233594753404805: 1, -2838663029721632918: 1, -5358825587431808290: 1, 4421254616062659296: 1, 4312394976376522492: 1, -1780546686493832872: 1, 5894258441458252804: 1, 2241144503569711492: 1, -4702636734758979593: 1, -3873389124285369982: 1, -4810652813129914460: 2, 4190803645941267740: 1, 4420726128461552055: 1, 3643772591052580973: 1, -6142254576424039680: 1, 3309944826964596303: 1, 5581808557368163038: 1, 3080171287306409354: 1, -9168414202712608032: 1, -498125121445117329: 1, -1809128157395373332: 1, -5163265989203114282: 1, -34488770188080543: 1, -5871784984758441949: 1, -5328663819022970397: 1, 4488397182914889656: 1, -3496632590121938350: 1, 5159346658833526703: 1, -7082002316062720320: 1, -7109975160529385789: 1, 6192976923969417715: 1, -1139486710702901615: 1, 6015543894815422362: 1, -1549607632612241418: 1, -323004954969598288: 1, 5434963275351364045: 1, 3631476903922067985: 1, 6759712050235809661: 1, 5407197431489557487: 1, 1037958919908444486: 1, -8217812236456625805: 1, 7657358448943720491: 1, 451142319874894935: 1, 4875768735673057421: 1, 4205026000914113414: 1, 6369887361660826424: 1, 5340521696270605229: 1, 867617765104028821: 1, -4903458639134355950: 1, -945543001688164958: 1, 2708982446719583566: 1, 7128026215855471437: 1, -6610295955772442530: 1, 6392074549014389944: 1, 5317109748460297762: 1, -4014058373445153108: 1, -8275039665156353338: 1, 6378752301273241166: 1, -3424220332872056000: 1, 8039706315243883883: 1, 2500314895081387951: 1, 1925488928503241905: 1, -821607739029025695: 1, -1076137166706009840: 1, 3377111833684065338: 1, 7990834647536579831: 1, 1206079257459146583: 1, 4023033904467574181: 1, -7309068923421318792: 1, -5775512093231990054: 1, 828679449110976202: 1, 8028617376532635689: 1, 1993292639010447714: 1, -3149528666790497540: 1, 776812654633256669: 1, 792034608498355637: 1, -3338682457910507788: 1, -2270841068847900513: 1, -972846921664820467: 1, 6229784073573732221: 1, -2524005983795469504: 1, -1920199341090698086: 1, -8422791364090819020: 1, 8136818920597202045: 1, -597040350247524537: 1, 1070884084169068668: 1, -1041042278745902556: 1, -83333637407182084: 1, 6479050588964871143: 1, -5143244007875316394: 1, 3666549731761377803: 1, -2388663671774396559: 1, 3829428859725096712: 1, 133082328049547295: 1, 4645770444564499000: 1, -4244508853620683925: 1, -5795242413593777475: 1, -476790221893546666: 1, 1883344819798017852: 1, -183099216425226760: 1, 11275561675152751: 1, -1701573149952780576: 1, 2939019793609055779: 1, -1651934734961350237: 1, 2040640792645704179: 1, 247526906172283048: 1, 6910195041231497034: 1, -3562253226177640096: 1, -4725424116829160167: 1, 6630219778766274501: 1, 2829290634917375449: 1, -4749170613260320854: 1, -3178213495677098288: 1, 863831847560209907: 1, -4667846588290220725: 1, 5253101592293167903: 1, -108281534276531494: 1, -6496914661653170262: 1, 7109331742742456399: 1, -1088444635005863144: 1, 9144152947085193061: 1, 4582328855194061075: 1, 2675998816076132964: 1, -3739371480464866336: 1, 7356831268552027869: 1, 3137066943315471784: 1, -7424433231527400331: 1, -1719131087483412120: 1, -5007608653478898011: 1, 5678872906851418919: 1, -7511801256827144216: 1, 4559688270991428412: 1, 5663091814633175837: 1, 5736034919510095575: 1, -4583411312646871453: 1, -4235665134570462413: 1, 6086402000046314108: 1, -7677687979680837708: 1, 4414036360564292599: 1, 4710701109891874210: 1, -3800520198452995022: 1, -717443010421913599: 1, -3675632289735372580: 1, -6992808336760627544: 1, -7291964478596186374: 1, 5082604299387528865: 1, -5481803351211144761: 1, -2280744173717903039: 1, -2617661132871342365: 1, -6361221660908611186: 1, 2306635634613453753: 1, -2735604334374728589: 2, -6008293151846057567: 1, 2174375182960170824: 1, 2949988230539455772: 1, 8027812858904977156: 1, 7048163513069349915: 1, -79475852046965874: 1, 1099076947719896856: 1, -5780002017645160238: 1, 2798165743212755630: 1, -3168729932941972045: 1, -1370990588135727199: 1, 3404626208068774762: 1, 6133537818944119770: 1, -3440480475679506128: 1, 4828485429898037635: 1, -6997452540876836156: 1, 2845606136863250497: 1, 2100181091134494838: 1, -5134321411458312924: 1, 3230148777020941987: 1, 8071933925421685144: 1, -3018656364495543463: 1, -478997798121384169: 1, 1876678646135972160: 1, 989778659623324353: 2, -7961114477436240947: 1, 4286476994611058056: 1, -4874331967007381051: 1, -7681519285468324387: 1, -2378313822420540701: 1, -3230833279688866306: 1, -7324230977903901999: 1, -4702164759779051714: 2, 4237896925995566007: 1, 5446013885756599850: 1, 8083799944847101043: 1, -1652096579425502791: 1, 7711937449247244832: 1, -1938320335935246392: 1, -6433329785766921309: 1, 1905870247871340116: 1, -6931497810264834934: 1, -271193428561684345: 1, -6036571521477393824: 1, 5662292922630110795: 1, -8249864955292463731: 1, 8852308514902872290: 1, -1567596742512723591: 1, 8850668323363767622: 1, -268453019013081528: 2, 1974654098388181337: 1, 2071229247571447830: 1, 627790514391004956: 1, -1712921495292217519: 1, 5636334338421080731: 1, 1233049377041756963: 1, 3095328185650826176: 1, -6063041246198532795: 1, 8295788969212848936: 1, -8319208967194140695: 1, -3298299820795766111: 1, 8726840906195961617: 1, -8763610049775213519: 1, -412311981692704151: 1, 2251104677521012096: 1, -4872626886708915763: 1, 3834276451915279275: 1, -5734440129048227884: 1, 4669355707095784113: 1, -1010320245020751912: 1, 8216875224833110824: 1, -2881013612464238115: 2, 2659335336157600251: 1, 6080918773403244480: 1, 1248549557160367518: 1, 6410452817166531998: 1, -1741520612098331778: 1, 7092925441514007712: 1, -6088606430438168961: 1, -7751604725580657377: 1, -5883039340442110413: 1, 1418778713000777970: 1, -2849664163288724368: 1, -5624068932865728274: 1, 8993138053894329986: 1, 8319114777743153926: 1, -163851125524838322: 1, 102521421282502916: 1, -693307189645430154: 1, -8181608919314635140: 1, -4175328958592300929: 1, -1579513891313654190: 1, 3357008271751082972: 1, -7946432708136267794: 1, 571726993019123569: 1, -918416418128719040: 1, -3061826349264033387: 1, 7521049593760228196: 1, 4674360214018470417: 1, -7480433435927897423: 1, 2378759648155087378: 1, -8063533955265550608: 1, -2922381014053011479: 1, 1941532593730518465: 1, 8492887398368714257: 1, -6294136853735447981: 1, -6639758823740800379: 1, -669557792951060230: 1, -7088029152960261598: 1, -7908704614416035161: 1, -8794471083214571819: 1, 3999511204916338286: 1, 2082737930719886670: 1, -7850701411238718746: 1, 3629689975670721972: 1, 5074938150053774857: 1, 3748875529398139311: 1, -3308257497745746942: 1, -2811311520750993654: 1, 507000677265586712: 1, 6108912918794605404: 1, 3185543614954714788: 1, -2590910536267976787: 1, -4049740945597821814: 1, -2778950503902117019: 1, -6866891884196129857: 1, 9184890637056011227: 1, 240434461045011747: 1, -6508215853534791084: 1, -769860683347527994: 1, -6571145157872484792: 1, -508016799137535407: 1, 8621259634617569064: 1, 5637026135633832200: 1, -2384244109832846164: 1, 1502608774782901208: 1, -3889994387997391316: 1, -5023709565915889414: 1, 2233026781613200075: 1, 6933168154801752768: 1, 1571588149521079152: 1, -8592349234217730744: 1, -9088211785951450047: 1, -6276238841974817383: 1, 6123839220308784252: 1, -6438418419245305409: 1, 5544758131347674226: 1, -271222266351523203: 1, -4547146293691530925: 1, -2398113754456967733: 1, 555577908094446924: 1, 1997735926809797959: 1, 9085430857671105366: 1, -7448859481210603084: 1, 1292341245664338816: 1, 1403040669798966893: 1, 6678151392935318702: 1, -5723813673814407755: 1, 202797822161056973: 1, -1716533789673122770: 1, 1034269125666299472: 2, 1548926623962074918: 1, -3450807625680765066: 1, -109348425569564811: 1, -6639964740759176915: 1, -3590450424031262262: 1, 9022145842724671568: 1, -7377088098189515369: 1, -1956132706603018148: 1, -4863869508378931993: 1, 4134690733720519145: 1, 4512644330150614257: 1, 8754060892571153453: 1, 4746833169184747451: 1, 2933247702130763366: 1, 8934297803471835126: 1, -8079765226327703692: 1, 3471729118518540987: 1, -8051409087636000825: 2, 1347949133298581447: 1, 3044894223090910799: 1, -422835136047395539: 1, -4148014045363062594: 1, -6611725149511343850: 1, -3840696879482655064: 1, -1212452326323649792: 1, -1609308251439344663: 1, -5101940378468312809: 1, 4048322366109267284: 1, -3609688646288032923: 1, -3174766588524572558: 1, 244767621249366962: 1, -3574120628680978030: 1, -8143102870115079226: 1, 7951528217028053947: 1, -5777964724122973803: 1, -1365331006019872620: 1, -7882059456255663233: 1, -1528548129604855444: 1, -8202997049315823126: 1, -4029319894035531338: 2, -5389306735497745137: 1, 2398762016794747839: 1, 304310262763740189: 1, -4472463245385633957: 1, 8067596512731959754: 1, 2596738288600117309: 1, 3184470306660313341: 1, -141135443198378298: 1, -3905879177502108001: 1, -4764415804701623235: 1, -3446600803234922813: 1, -2599664583811452369: 1, 6138919934353445295: 1, 203338291371913340: 1, -2234835286324724824: 1, -8063834767786026182: 1, 2418936059463900377: 1, -6578524474593693878: 1, 8545963094801079175: 1, 3272818744637014490: 1, 2605771719667343575: 1, -1152828579447154037: 1, -3574898870996005659: 1, -5651380639943147747: 1, 6958054283303633503: 1, 3584760134859783153: 1, -3448074136656561712: 1, 8711970650608358640: 1, 909857114102953211: 1, -3608376032663344776: 1, -8652511952785195272: 1, 6560117581560214429: 1, 6981498189656917553: 1, 8523254138830225643: 1, 4972274812356262932: 1, -7636893389134800387: 1, -7040261212186833490: 1, 1605527304364940000: 1, 8240973554428020356: 1, 4724147459087980028: 1, 6615957214906199694: 1, 4301016691354225923: 1, -71582286965455025: 1, -3330991117186718365: 1, -195519098474860309: 1, 5628789382704787419: 1, 1840849659021562638: 1, 6605900472819921535: 1, 3962261390456932656: 1, -7256056065165425574: 1, -6176466413597249436: 1, -2223452938620628278: 1, -4493947698393876377: 1, -5960752990306241082: 1, -4419649684265368019: 1, -2745026915712913743: 1, 624737418116060337: 1, -752963392348818040: 1, -976044994146147360: 1, -2937086209435923295: 1, 4441433156326298865: 1, 3087929174126271303: 1, 6731529203141222225: 1, -2760996326008425182: 1, -8113691733231041354: 1, -3843914179603523954: 1, -8796657295025449896: 1, -8589751620075251707: 1, 8625280356654857906: 1, 7093188811570060609: 1, 2659943935546417078: 1, -4029509059047633713: 1, -558743113677674644: 1, 4744113519950309609: 1, 6518987279679667909: 1, 1997528452612653079: 1, 4401699918054895688: 1, 3416652053808062313: 1, 4844294008164504801: 1, 6779068486494853711: 1, -564260852465750131: 1, 1340286411573666960: 1, -3428377060480318416: 1, 5960695691879230896: 1, -3358080218553741291: 1, -6333890681428870884: 1, 4055141819778447913: 1, -3206822722210706427: 1, 5568669381345763200: 1, -244705746086878086: 1, -8507939650877628959: 1, 759448056796458562: 1, -4444777825792263062: 1, -1162106931068503682: 1, 9165716548744551337: 2, -943034146111438448: 1, 6525417142679226136: 1, -1597488828936942204: 1, 2360891719019859549: 1, -3328822346407660699: 1, 6945335918538200243: 1, -2732128085585644400: 1, 4189476058077987897: 1, -5435773704256659703: 1, -6005243010656230834: 1, -3665318770149867004: 1, 2596852758413421347: 1, 7024757239091859388: 1, 1973309501363781043: 1, -3502336883622271924: 1, -6538127535533315602: 1, -2138720074604204861: 1, -2633224023753607455: 1, 3861438176792289351: 1, 5017197072604856444: 1, 4759047838660164437: 1, -5404560730803962257: 1, -4706468854727133102: 1, 5458813989387060367: 1, -8666636303937695405: 1, -9093496050240783309: 1, 6583262848730557: 2, 5599510821483315402: 1, 2541019903024283168: 1, -8960930091442340165: 1, 7978395469073764854: 1, -8216205489099643821: 1, 4179813788893263725: 1, -4402896036573701246: 1, -1227979567843870726: 1, 7292204325854618521: 1, -7909349510057515863: 1, 8800098794359750865: 1, 300691425144593923: 1, -2995855346611980432: 1, -5792623998143782390: 1, 2487240716977326532: 1, -7763265575104999579: 1, -6462560047459691847: 1, -3827771670348125850: 1, -1037556682936775963: 1, 7615147500755076151: 1, -6737600867777799949: 1, -8616279474572234249: 1, 4326322973732423847: 1, -7817062015098795784: 1, 8446211663957245136: 1, -3836261440825617157: 1, -2508120630970019806: 1, -2226926003688380704: 1, 8067678576741771705: 1, -157182852091706519: 1, 4532473737966290208: 1, -1134676547039154912: 1, 6468446712822544483: 1, -5552875973923601688: 1, 1719753320280907312: 1, -6304978667624083267: 1, 2138506012562250226: 1, 2051908641413422516: 1, -6069878609520409683: 1, 401607353084765022: 1, 5486186214991036003: 1, 5216862755310093372: 1, -8098433266389628647: 1, 129527704033736274: 1, 1107317917640141108: 1, -2934186011173459634: 1, 2964746644309172586: 1, -7936157103837476092: 1, 6018925263579266687: 1, 8424011230653963183: 1, 6727894145776147763: 1, -8801207588308097248: 1, -8393288237396069125: 1, -6454642646379049540: 1, -584602012246720504: 1, -6099242001232489988: 1, -6296382717616748505: 1, 720945670046061886: 1, 3957638783010642798: 1, -3191696254826225084: 1, -4110433062679792415: 1, -3514668964597429999: 1, 394381867847963120: 1, 7229096056569192505: 2, -4927538870398985643: 1, 7247719394433493849: 1, -997600607174724315: 1, 509563424149330743: 1, 4728723254240983141: 1, 8889778604591870406: 1, -4812778564364922527: 1, 551760912922796376: 1, -5003275399161171098: 1, 758176086854087960: 1, -8020730261697622788: 1, 1711114583138414169: 1, -3440172550829103235: 1, -7830746802783732216: 1, -3282530481665457882: 1, 713243793046105259: 1, -6491650631940343593: 1, -7712583880100850648: 1, -7051456892208606004: 1, 2496044807685757926: 1, -3858195644094724001: 1, 5642849027753874878: 1, -5521437872915609775: 1, -4354860043659362335: 1, -3322086629419568822: 1, 4577504220248541230: 1, -3783857772130014146: 1, -1212534671935019142: 1, 5039070589622116223: 1, 1003107031518479927: 1, -5918058044087631639: 1, 910212946848414132: 1, 1710773821297475844: 1, 2466176831638856396: 1, -3839856182941643113: 1, -2461210832610396843: 1, -5050885901253896336: 1, -3229498717638788378: 1, 6767951285824989437: 1, -5167731392094189093: 1, 3166316084102435661: 1, -1084675126739837951: 1, -5325471815278199699: 1, -7692593919857489667: 1, 3807731790676089047: 1, 8547387439475752343: 1, -4240370061488330852: 1, 3788481738203903392: 1, 8580751281923707638: 1, 4361361602408731926: 1, 8834271362378562022: 1, 6140195563664444091: 1, -631654087223595576: 1, -4955027645601067045: 1, -3341625858601628474: 1, -6338382412300663628: 1, 6509077023714329692: 1, 5124671968400080990: 1, -5178498117329242120: 1, -3948911694753125108: 1, -7445853121592989686: 1, -5706488219064807699: 1, 3647438028014046992: 1, -1875132340240926475: 1, -4303817324934865490: 1, 5537957552610317684: 1, -4698540842799079471: 1, 7269309053529101252: 1, 6235943999576155920: 1, -5657716691635083568: 1, 6479713261163261872: 1, -4783042482050836757: 1, -258038815636539037: 1, -4009045158169494008: 1, 4046143166561850939: 1, 8529798019064391622: 1, 6812063218433598239: 1, 7638501072833648755: 1, 6875949012604790893: 1, 3046975322023341425: 1, 8906987217232619167: 1, 3198099377582238166: 1, -6429086889647522059: 1, 1791745235826405446: 1, -6126235341819224206: 1, 5793133023840695500: 1, 99697397095754181: 1, 3342566831102465164: 1, -9148864273886196963: 1, -307115911068805

In [31]:
for country, hashes in hash_counts.items():
    non_unique = len([h for h, hc in hashes.items() if hc > 1])
    print(f'{country=}, {len(hashes)=}, {non_unique=} ({non_unique * 100 // len(hashes)}%)')

country='SG', len(hashes)=1233, non_unique=24 (1%)
country='USA', len(hashes)=3593, non_unique=388 (10%)
country='UK', len(hashes)=1094, non_unique=12 (1%)
country='CAN', len(hashes)=3746, non_unique=226 (6%)

## JOIN

In [3]:
lb_join_gt = pd.read_csv(join_lb_gt_path)
lb_join_gt

,query_table,candidate_table,query_column,candidate_column
0,CAN_CSV0000000000001724__13.csv,CAN_CSV0000000000001787__9.csv,RentLocation,RentLocation
1,UK_CSV0000000000003896__7.csv,UK_CSV0000000000002010__11.csv,Post-Op Q Anxiety,Post-Op Q Anxiety
2,UK_CSV0000000000003896__7.csv,UK_CSV0000000000002010__11.csv,Post-Op Q Wound,Post-Op Q Wound
3,USA_CSV0000000000037101__16.csv,USA_CSV0000000000033847__23.csv,STD_VOLUME_GROUP,STD_VOLUME_GROUP
4,USA_CSV0000000000037101__16.csv,USA_CSV0000000000033847__23.csv,ROUTE_SIGNING,ROUTE_SIGNING
...,...,...,...,...
42558,CAN_CSV0000000000013788.csv,CAN_CSV0000000000001071.csv,"ï»¿""REF_DATE""","ï»¿""REF_DATE"""
42559,CAN_CSV0000000000013788.csv,CAN_CSV0000000000000660.csv,"ï»¿""REF_DATE""","ï»¿""REF_DATE"""
42560,CAN_CSV0000000000013788.csv,CAN_CSV0000000000013712.csv,"ï»¿""REF_DATE""","ï»¿""REF_DATE"""
42561,CAN_CSV0000000000013788.csv,CAN_CSV0000000000000857.csv,"ï»¿""REF_DATE""","ï»¿""REF_DATE"""
42562,CAN_CSV0000000000013788.csv,CAN_CSV0000000000000701.csv,"ï»¿""REF_DATE""","ï»¿""REF_DATE"""

### Are present all the tables from the Ground Truth?

Answer: YES, all the tables listed into the JOIN Ground Truth are also contained into the relative country dataset

In [4]:
all_join_table_ids = set(filter(lambda s: '__' not in s, chain(*lb_join_gt.values.tolist())))
len(all_join_table_ids)

2508

In [11]:
join_table_ids_by_country = {
    country: {s for s in all_join_table_ids if country in s}
    for country in ['SG', 'USA', 'UK', 'CAN']
}

In [12]:
for country, tables in join_table_ids_by_country.items():
    print(f'{country=}, {len(tables)=}')

country='SG', len(tables)=50
country='USA', len(tables)=334
country='UK', len(tables)=103
country='CAN', len(tables)=961

In [13]:
for country, tables in join_table_ids_by_country.items():
    with zipfile.ZipFile(f'{data_path}/datasets/datasets_{country}.zip') as z:
        names = {f.removeprefix(f'datasets_{country}/') for f in z.namelist()}
        names.remove('')

        diff = tables.difference(names)
        print(f'{country=}, {len(diff)=}')

country='SG', len(diff)=0
country='USA', len(diff)=0
country='UK', len(diff)=0
country='CAN', len(diff)=0

### How many Ground Truth pairs have different names for query and candidate columns?

Answer: None

In [8]:
lb_join_gt[lb_join_gt['query_column'] != lb_join_gt['candidate_column']]

Empty DataFrame
Columns: [query_table, candidate_table, query_column, candidate_column]
Index: []

### There are some identical query and candidate tables?

Answer: the 4% of the total JOIN pairs into the Ground Truth is actually a no-sense join on the same column of the same table

In [9]:
lb_join_gt[lb_join_gt['query_table'] == lb_join_gt['candidate_table']].shape[0] * 100 / lb_join_gt.shape[0]

4.010525573855227

In [10]:
lb_join_gt[(lb_join_gt['query_table'] == lb_join_gt['candidate_table']) & (lb_join_gt['query_column'] != lb_join_gt['candidate_column'])]

Empty DataFrame
Columns: [query_table, candidate_table, query_column, candidate_column]
Index: []

## UNION

In [12]:
lb_union_gt = pd.read_csv(union_lb_gt_path)
lb_union_gt

                       query_table              candidate_table
0      CAN_CSV0000000000000474.csv  CAN_CSV0000000000004972.csv
1      CAN_CSV0000000000000474.csv  CAN_CSV0000000000013001.csv
2      CAN_CSV0000000000000474.csv  CAN_CSV0000000000002292.csv
3      CAN_CSV0000000000000474.csv  CAN_CSV0000000000027218.csv
4      CAN_CSV0000000000000474.csv  CAN_CSV0000000000005832.csv
...                            ...                          ...
49510  USA_CSV0000000000037302.csv  USA_CSV0000000000037302.csv
49511  USA_CSV0000000000037322.csv  USA_CSV0000000000037327.csv
49512  USA_CSV0000000000037322.csv  USA_CSV0000000000037322.csv
49513  USA_CSV0000000000037327.csv  USA_CSV0000000000037327.csv
49514  USA_CSV0000000000037327.csv  USA_CSV0000000000037322.csv

[49515 rows x 2 columns]

### There are pairs of identical tables?

Answer: YES, the 5% (2688) pairs of tables from the Ground Truth is no-sense, since it is references the same identical table

In [13]:
lb_union_gt[lb_union_gt['query_table'] == lb_union_gt['candidate_table']].shape[0] * 100 / lb_union_gt.shape[0]

5.428657982429566

### All the tables are present into the provided dataset?

Filtering the slices

Answer: YES, it seems that all the tables in the UNION Ground Truth are present into the relative country Open Data

In [14]:
all_union_table_ids = set(filter(lambda s: '__' not in s, chain(*lb_union_gt.values.tolist())))
len(all_union_table_ids)

3784

In [15]:
union_table_ids_by_country = {
    country: {s for s in all_union_table_ids if country in s}
    for country in ['SG', 'USA', 'UK', 'CAN']
}

In [16]:
for country, tables in union_table_ids_by_country.items():
    print(f'{country=}, {len(tables)=}')

country='SG', len(tables)=355
country='USA', len(tables)=700
country='UK', len(tables)=234
country='CAN', len(tables)=2495

In [17]:
for country, tables in union_table_ids_by_country.items():
    with zipfile.ZipFile(f'{data_path}/datasets/datasets_{country}.zip') as z:
        names = {f.removeprefix(f'datasets_{country}/') for f in z.namelist()}
        names.remove('')

        diff = tables.difference(names)
        print(f'{country=}, {len(diff)=}')

country='SG', len(diff)=0
country='USA', len(diff)=0
country='UK', len(diff)=0
country='CAN', len(diff)=0