In [18]:
import os
import bidict
import pickle
import duckdb

import jsonlines
import pandas as pd
import polars as pl

from orqa.utils import sanitize_string, is_num

In [2]:
tables_path     = '../data/datasets/CAN/tables/tables_from10000_to15000'
metadata_path   = '../data/datasets/CAN/metadata/metadata_from10000_to15000'

db_path         = '../data/datasets/CAN/database/CAN.db'
valdict_path    = '../data/datasets/CAN/database/values_dict.pickle'

In [3]:
table_ids = list(sorted(os.listdir(tables_path), reverse=True))
len(table_ids)

3689

In [29]:
with jsonlines.open(metadata_path) as fr:
    metadata = {rsc['id']: md for md in fr.iter() for rsc in md['resources'] if rsc['format'] == 'CSV'}

In [4]:
with open(valdict_path, 'rb') as fr:
    values = pickle.load(fr)

In [30]:
type(values), len(values.values()), len(set(values.values())), len(metadata)

(bidict.bidict, 5961157, 5961157, 4203)

In [6]:
from itertools import chain

def get_table_values(table_id):
    df = pl.read_parquet(f'{tables_path}/{table_id}')
    df = df[[s.name for s in df if not (s.null_count() == df.height)]]

    return set(
        filter(
            lambda v: v not in values and not is_num(v), 
            map(
                lambda s: sanitize_string(str(s)), 
                chain(*(
                    df.select(col).drop_nans().drop_nulls().unique().get_column(col).to_list() 
                    for col in df.columns
                    )
                )                
            )
        )
    )

In [7]:
con = duckdb.connect(db_path, read_only=True)

In [195]:
i_tab_q = 5
qdf = pl.read_parquet(f"{tables_path}/{table_ids[i_tab_q]}")
qdf

shape: (71_934, 15)
┌────────────┬────────────┬───────────┬─────────┬───┬────────────┬────────────┬────────┬───────────┐
│ Sample No. ┆ Region -   ┆ Commodity ┆ Denrée  ┆ … ┆ Component  ┆ Composant  ┆ Amount ┆ Report    │
│  No. déc ┆ Région     ┆ ---       ┆ ---     ┆   ┆ ---        ┆ ---        ┆ ---    ┆ Unit -    │
│ hantillon  ┆ ---        ┆ str       ┆ str     ┆   ┆ str        ┆ str        ┆ f64    ┆ Unité de  │
│ ---        ┆ str        ┆           ┆         ┆   ┆            ┆            ┆        ┆ rapport   │
│ str        ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆ ---       │
│            ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆ str       │
╞════════════╪════════════╪═══════════╪═════════╪═══╪════════════╪════════════╪════════╪═══════════╡
│ CFP2020-00 ┆ ATLANTIC   ┆ Dairy     ┆ Laitier ┆ … ┆ 19-Nortest ┆ 19-Nortest ┆ 0.0    ┆ µg/g      │
│ 01         ┆            ┆           ┆         ┆   ┆ osterone   ┆ ostérone   ┆        ┆           │
│ CFP2020-00 ┆ ATLANTIC   ┆ Dairy     ┆ Laitier ┆ … ┆ 2,3,4,5    ┆ 2,3,4,5    ┆ 0.0    ┆ µg/g      │
│ 01         ┆            ┆           ┆         ┆   ┆ TetraChlor ┆ Tétrachlor ┆        ┆           │
│            ┆            ┆           ┆         ┆   ┆ ophenol    ┆ ophénol    ┆        ┆           │
│ CFP2020-00 ┆ ATLANTIC   ┆ Dairy     ┆ Laitier ┆ … ┆ 2,3,4,6    ┆ 2,3,4,6    ┆ 0.0    ┆ µg/g      │
│ 01         ┆            ┆           ┆         ┆   ┆ TetraChlor ┆ Tétrachlor ┆        ┆           │
│            ┆            ┆           ┆         ┆   ┆ ophenol    ┆ ophénol    ┆        ┆           │
│ CFP2020-00 ┆ ATLANTIC   ┆ Dairy     ┆ Laitier ┆ … ┆ 2,3,5,6    ┆ 2,3,5,6    ┆ 0.0    ┆ µg/g      │
│ 01         ┆            ┆           ┆         ┆   ┆ TetraChlor ┆ Tétrachlor ┆        ┆           │
│            ┆            ┆           ┆         ┆   ┆ ophenol    ┆ ophénol    ┆        ┆           │
│ CFP2020-00 ┆ ATLANTIC   ┆ Dairy     ┆ Laitier ┆ … ┆ 20-Dihydro ┆ 20-Dihydro ┆ 0.0    ┆ µg/g      │
│ 01         ┆            ┆           ┆         ┆   ┆ prednisolo ┆ prednisolo ┆        ┆           │
│            ┆            ┆           ┆         ┆   ┆ ne         ┆ ne         ┆        ┆           │
│ …          ┆ …          ┆ …         ┆ …       ┆ … ┆ …          ┆ …          ┆ …      ┆ …         │
│ CFP2020-01 ┆ ATLANTIC   ┆ IMFD      ┆ DAIM    ┆ … ┆ Vinclozoli ┆ Vinclozoli ┆ 0.0    ┆ µg/g      │
│ 75         ┆            ┆           ┆         ┆   ┆ n          ┆ ne         ┆        ┆           │
│ CFP2020-01 ┆ ATLANTIC   ┆ IMFD      ┆ DAIM    ┆ … ┆ Zengxiaoan ┆ zengxiaoan ┆ 0.0    ┆ µg/g      │
│ 75         ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆           │
│ CFP2020-01 ┆ ATLANTIC   ┆ IMFD      ┆ DAIM    ┆ … ┆ Zinc       ┆ Zinc       ┆ 22.3   ┆ µg/g      │
│ 75         ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆           │
│ CFP2020-01 ┆ ATLANTIC   ┆ IMFD      ┆ DAIM    ┆ … ┆ Zinophos   ┆ Zinophos   ┆ 0.0    ┆ µg/g      │
│ 75         ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆           │
│ CFP2020-01 ┆ ATLANTIC   ┆ IMFD      ┆ DAIM    ┆ … ┆ Zoxamide   ┆ Zoxamide   ┆ 0.0    ┆ µg/g      │
│ 75         ┆            ┆           ┆         ┆   ┆            ┆            ┆        ┆           │
└────────────┴────────────┴───────────┴─────────┴───┴────────────┴────────────┴────────┴───────────┘

In [197]:
bad_columns_tokens = {'id', 'date'}

for i_col in range(len(qdf.columns)):
    if 'id' in qdf.columns[i_col].lower():
        continue
    print(i_col, qdf.columns[i_col])
    if any(tok in qdf.columns[i_col].lower() for tok in bad_columns_tokens):
        continue
    qcol = map(lambda v: sanitize_string(str(v)), set(qdf.to_series(i_col)))
    q = list(map(lambda v: str(values[v]), filter(lambda v: v in values, qcol)))
    if not q: continue
    res = con.sql(f"""
            SELECT TableId, ColumnId, COUNT(DISTINCT CellValue) AS intersec FROM AllTables
            WHERE CellValue IN ({','.join(q)})
            AND TableId <> {i_tab_q}
            GROUP BY TableId, ColumnId
            ORDER BY COUNT(DISTINCT CellValue) DESC
            LIMIT 10;
    """)
    print(res)

0 Sample No.  No. déchantillon
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┴──────────┴──────────┤
│            0 rows             │
└───────────────────────────────┘

1 Region - Région
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    2953 │        0 │        1 │
│    1086 │        0 │        1 │
│     987 │        0 │        1 │
│     685 │        1 │        1 │
│    1152 │        0 │        1 │
│    1026 │        0 │        1 │
│    3239 │        0 │        1 │
│     998 │        0 │        1 │
│     959 │        0 │        1 │
│    3515 │        0 │        1 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

2 Commodity
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    2880 │        0 │        1 │
│     950 │        0 │        1 │
│    1975 │        2 │        1 │
│      40 │        0 │        1 │
│    1523 │        2 │        1 │
│    2856 │        2 │        1 │
│    3004 │        0 │        1 │
│    3074 │        2 │        1 │
│    1590 │        0 │        1 │
│     220 │        0 │        1 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

3 Denrée
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    2856 │        3 │        1 │
│    3074 │        3 │        1 │
│     327 │        3 │        1 │
│    2833 │        3 │        1 │
│    1523 │        3 │        1 │
│    1975 │        3 │        1 │
└─────────┴──────────┴──────────┘

4 Function
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    2195 │        2 │        3 │
│    1945 │        2 │        3 │
│    3082 │        2 │        3 │
│    2349 │        2 │        3 │
│    2058 │        2 │        3 │
│    2170 │        2 │        3 │
│     327 │        4 │        3 │
│    1806 │        2 │        3 │
│    3015 │        2 │        3 │
│     685 │        2 │        3 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

5 Fonction
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    3074 │        5 │        3 │
│    2945 │        3 │        3 │
│     283 │        3 │        3 │
│     327 │        5 │        3 │
│    1945 │        3 │        3 │
│    2749 │        3 │        3 │
│     189 │        3 │        3 │
│    2195 │        3 │        3 │
│    1523 │        5 │        3 │
│     269 │        3 │        3 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

6 Origin
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│     269 │        4 │        7 │
│     189 │        4 │        6 │
│    2856 │        6 │        6 │
│    2749 │        4 │        6 │
│     283 │        4 │        6 │
│     685 │        4 │        6 │
│    3070 │        4 │        6 │
│    2620 │        4 │        6 │
│    1840 │        3 │        5 │
│    3027 │        3 │        5 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

7 Origine
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│     269 │        5 │        7 │
│    2856 │        7 │        6 │
│     189 │        5 │        6 │
│    2620 │        5 │        6 │
│     283 │        5 │        6 │
│    3070 │        5 │        6 │
│    2749 │        5 │        6 │
│     685 │        5 │        6 │
│    1945 │        5 │        5 │
│    1806 │        5 │        5 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

8 Product
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    1806 │        6 │        3 │
│    2856 │        8 │        2 │
│     685 │        6 │        1 │
│     813 │        0 │        1 │
│     215 │        0 │        1 │
│     344 │        0 │        1 │
│    1524 │        0 │        1 │
└─────────┴──────────┴──────────┘

9 Produit
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    1806 │        7 │        3 │
│    2856 │        9 │        2 │
│    1040 │        0 │        1 │
│     685 │        7 │        1 │
│      40 │        0 │        1 │
└─────────┴──────────┴──────────┘

10 Date Sampled  Date déchantillonage
11 Component
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│     950 │        3 │      255 │
│    2880 │        3 │      251 │
│    3004 │        3 │      251 │
│    1590 │        3 │      205 │
│    2760 │        3 │      183 │
│     220 │        3 │      182 │
│    1524 │        3 │      145 │
│     549 │        1 │      118 │
│     813 │        3 │       92 │
│    2507 │        2 │       85 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

12 Composant
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│    1524 │        3 │      225 │
│     813 │        3 │      163 │
│    3004 │        3 │      144 │
│    2880 │        3 │      140 │
│     950 │        3 │      139 │
│    1590 │        3 │      113 │
│     220 │        3 │       95 │
│    2760 │        3 │       91 │
│     344 │        2 │       76 │
│     549 │        1 │       74 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

13 Amount
14 Report Unit - Unité de rapport
┌─────────┬──────────┬──────────┐
│ TableId │ ColumnId │ intersec │
│  int32  │  int32   │  int64   │
├─────────┼──────────┼──────────┤
│     327 │       16 │        1 │
│    1523 │       16 │        1 │
│    2856 │       16 │        1 │
│     550 │       14 │        1 │
│    2195 │       14 │        1 │
│    1806 │       14 │        1 │
│    1601 │       16 │        1 │
│    1139 │       16 │        1 │
│     685 │       14 │        1 │
│    3074 │       16 │        1 │
├─────────┴──────────┴──────────┤
│ 10 rows             3 columns │
└───────────────────────────────┘

In [198]:
i_tab_res = 269
r_df = pl.read_parquet(f"{tables_path}/{table_ids[i_tab_res]}")
r_df

shape: (1_608, 16)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sample No. ┆ Region -  ┆ Function ┆ Fonction ┆ … ┆ Composant ┆ Result -  ┆ Report    ┆ Plan Code │
│  No. déc ┆ Région    ┆ ---      ┆ ---      ┆   ┆ ---       ┆ Résultat  ┆ Unit -    ┆ - Code du │
│ hantillon  ┆ ---       ┆ str      ┆ str      ┆   ┆ str       ┆ ---       ┆ Unité de  ┆ régime    │
│ ---        ┆ str       ┆          ┆          ┆   ┆           ┆ f64       ┆ rapport   ┆ ---       │
│ str        ┆           ┆          ┆          ┆   ┆           ┆           ┆ ---       ┆ str       │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆ str       ┆           │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0001       ┆           ┆          ┆          ┆   ┆ A         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Éther dig ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0001       ┆           ┆          ┆          ┆   ┆ lycidyliq ┆           ┆           ┆ 1         │
│            ┆           ┆          ┆          ┆   ┆ ue de     ┆           ┆           ┆           │
│            ┆           ┆          ┆          ┆   ┆ bisphé…   ┆           ┆           ┆           │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0001       ┆           ┆          ┆          ┆   ┆ F         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0001       ┆           ┆          ┆          ┆   ┆ S         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0001D      ┆           ┆          ┆          ┆   ┆ A         ┆           ┆           ┆ 1         │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ C2020BPHA0 ┆ WEST      ┆ Unknown  ┆ inconnu  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0399       ┆           ┆          ┆          ┆   ┆ S         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0400       ┆           ┆          ┆          ┆   ┆ A         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Éther dig ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0400       ┆           ┆          ┆          ┆   ┆ lycidyliq ┆           ┆           ┆ 1         │
│            ┆           ┆          ┆          ┆   ┆ ue de     ┆           ┆           ┆           │
│            ┆           ┆          ┆          ┆   ┆ bisphé…   ┆           ┆           ┆           │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0400       ┆           ┆          ┆          ┆   ┆ F         ┆           ┆           ┆ 1         │
│ C2020BPHA0 ┆ WEST      ┆ Import   ┆ importé  ┆ … ┆ Bisphénol ┆ 0.0       ┆ µg/g      ┆ 2020_SB45 │
│ 0400       ┆           ┆          ┆          ┆   ┆ S         ┆           ┆           ┆ 1         │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [183]:
r_df.to_series(6).is_null().sum() / r_df.shape[0]

0.8715203426124197

In [134]:
def get_resource_metadata(rsc_id):
    return next(filter(lambda r: r['id'] == table_ids[rsc_id].removesuffix('.parquet'), metadata[table_ids[rsc_id].removesuffix('.parquet')]['resources']))

In [199]:
print(get_resource_metadata(i_tab_q)['name'])
print(get_resource_metadata(i_tab_res)['name'])
print('-' * 20)
print(metadata[table_ids[i_tab_q].removesuffix('.parquet')]['title'])
print(metadata[table_ids[i_tab_res].removesuffix('.parquet')]['title'])

Children's Food Project - 2020 Data
Open Data for Chemistry Targeted Surveys - 2020-21 Bisphenol A and BPA Alternatives in Selected Canned Foods
--------------------
Children's Food Project - 2020 Data
Open Data for Chemistry Targeted Surveys - 2020-21 Bisphenol A and BPA Alternatives in Selected Canned Foods

In [201]:
print(metadata[table_ids[i_tab_q].removesuffix('.parquet')]['notes'])
print('-' * 10)
print(metadata[table_ids[i_tab_res].removesuffix('.parquet')]['notes'])

The main objectives of the 2020 CFP were to:

collect data and assess the compliance of infant foods to Canadian standards for residues of pesticides, veterinary drugs and metals/elements
collect data on aflatoxin M1 levels in yogurt/yogurt beverages and pudding
Previous years have analyzed pesticides, metals/elements, veterinary drug residues, aflatoxin M1 and environmental contaminants.

In the 2020 CFP, a total of 175 samples of children's foods were purchased in Halifax, Nova Scotia in October, 2020. These samples included:

children's cereals
yogurt/yogurt beverages
pudding
fruit snacks
granola/cereal bars
----------
​This dataset file and the results containe support and correlate with the CFIA Food Safety Bulletin Report - Bisphenol A and BPA Alternatives in Selected Canned Foods - April 1, 2020 to March 31, 2021.

In [203]:
metadata[table_ids[i_tab_q].removesuffix('.parquet')]

{'association_type': [],
 'audience': [],
 'author': None,
 'author_email': None,
 'collection': 'primary',
 'contributor': {'fr': '', 'en': ''},
 'creator': '',
 'creator_user_id': '2dc5a12f-2a6f-4822-8514-165ea6bb05d9',
 'data_series_issue_identification': {'fr': 'CFIA-ACIA-1264',
  'en': 'CFIA-ACIA-1264'},
 'data_series_name': {'fr': '', 'en': ''},
 'date_published': '2022-08-18 00:00:00',
 'digital_object_identifier': '',
 'display_flags': [],
 'frequency': 'not_planned',
 'geographic_region': [],
 'id': 'b1974f49-da37-4783-8705-97bfe6720a2c',
 'imso_approval': 'true',
 'isopen': False,
 'jurisdiction': 'federal',
 'keywords': {'fr': ['enfants',
   'bébés',
   'chimie',
   'salubrité alimentaire',
   'résidus chimiques'],
  'en': ['food safety',
   'chemistry',
   'children',
   'infant',
   'chemical residues']},
 'license_id': 'ca-ogl-lgo',
 'license_title': 'Open Government Licence - Canada',
 'license_url': 'https://open.canada.ca/en/open-government-licence-canada',
 'maintainer': None,
 'maintainer_contact_form': {},
 'maintainer_email': 'cfia.openagency-agenceouverte.acia@inspection.gc.ca',
 'metadata_contact': {},
 'metadata_created': '2022-08-18T20:17:03.873262',
 'metadata_modified': '2024-11-21T01:46:52.790144',
 'name': 'b1974f49-da37-4783-8705-97bfe6720a2c',
 'notes': "The main objectives of the 2020 CFP were to:\r\n\r\ncollect data and assess the compliance of infant foods to Canadian standards for residues of pesticides, veterinary drugs and metals/elements\r\ncollect data on aflatoxin M1 levels in yogurt/yogurt beverages and pudding\r\nPrevious years have analyzed pesticides, metals/elements, veterinary drug residues, aflatoxin M1 and environmental contaminants.\r\n\r\nIn the 2020 CFP, a total of 175 samples of children's foods were purchased in Halifax, Nova Scotia in October, 2020. These samples included:\r\n\r\nchildren's cereals\r\nyogurt/yogurt beverages\r\npudding\r\nfruit snacks\r\ngranola/cereal bars",
 'notes_translated': {'fr': "Les principaux objectifs du PAE 2020 étaient les suivants :\r\n\r\nrecueillir des données et évaluer la conformité des aliments pour nourrissons aux normes canadiennes en matière de résidus de pesticides, de médicaments vétérinaires et de métaux/éléments;\r\nrecueillir des données sur les concentrations d'aflatoxine M1 dans le yogourt, le yogourt à boire et les poudings.\r\nAu cours des années précédentes, des analyses de dépistage de pesticides, de métaux et d'éléments, de résidus de médicaments vétérinaires, d'aflatoxine M1 et de contaminants environnementaux ont été effectuées.\r\n\r\nDans le cadre du PAE 2020, un total de 175 échantillons d'aliments destinés aux enfants ont été achetés dans la région de Halifax (Nouvelle-Écosse) en octobre 2020. Ces échantillons comprenaient :\r\n\r\ndes céréales pour enfants\r\ndu yogourt et du yogourt à boire\r\ndes poudings\r\ndes collations aux fruits\r\ndes barres de granola/céréales",
  'en': "The main objectives of the 2020 CFP were to:\r\n\r\ncollect data and assess the compliance of infant foods to Canadian standards for residues of pesticides, veterinary drugs and metals/elements\r\ncollect data on aflatoxin M1 levels in yogurt/yogurt beverages and pudding\r\nPrevious years have analyzed pesticides, metals/elements, veterinary drug residues, aflatoxin M1 and environmental contaminants.\r\n\r\nIn the 2020 CFP, a total of 175 samples of children's foods were purchased in Halifax, Nova Scotia in October, 2020. These samples included:\r\n\r\nchildren's cereals\r\nyogurt/yogurt beverages\r\npudding\r\nfruit snacks\r\ngranola/cereal bars"},
 'num_resources': 1,
 'num_tags': 0,
 'org_section': {'fr': 'Science', 'en': 'Science'},
 'org_title_at_publication': {'fr': "Agence canadienne d'inspection des aliments",
  'en': 'Canadian Food Inspection Agency'},
 'organization': {'id': '90D94FD0-5E79-4DBB-AF2A-B1DC881749FA',
  'name': 'cfia-acia',
  'title': "Canadian Food Inspection Agency | Agence canadienne d'inspection des aliments",
  'type': 'organization',
  'description': '',
  'image_url': '',
  'created': '2016-09-23T17:25:02.773619',
  'is_organization': True,
  'approval_status': 'approved',
  'state': 'active'},
 'owner_org': '90D94FD0-5E79-4DBB-AF2A-B1DC881749FA',
 'place_of_publication': [],
 'portal_release_date': '2022-08-18',
 'position_name': {},
 'private': False,
 'program_page_url': {'fr': 'https://inspection.canada.ca/salubrite-alimentaire-pour-l-industrie/chimie-et-microbiologie-alimentaires/bulletin-d-enquete-et-rapports-d-analyse-sur-la-sa/projet-sur-les-aliments-destines-aux-enfants-2020/fra/1657134074819/1657134075190',
  'en': 'https://inspection.canada.ca/food-safety-for-industry/food-chemistry-and-microbiology/food-safety-testing-bulletin-and-reports/children-s-food-project-2020/eng/1657134074819/1657134075190'},
 'ready_to_publish': 'true',
 'restrictions': 'unrestricted',
 'spatial': '',
 'spatial_representation_type': [],
 'state': 'active',
 'subject': ['science_and_technology'],
 'title': "Children's Food Project - 2020 Data",
 'title_translated': {'fr': 'Projet sur les aliments destinés aux enfants — Données 20120',
  'en': "Children's Food Project - 2020 Data"},
 'topic_category': [],
 'type': 'dataset',
 'url': None,
 'version': None,
 'resources': [{'cache_last_updated': None,
   'cache_url': None,
   'character_set': '',
   'created': '2022-08-18T20:17:04.280616',
   'data_quality': [],
   'datastore_active': False,
   'datastore_contains_all_records_of_source_file': False,
   'date_published': '',
   'description': None,
   'format': 'CSV',
   'hash': '',
   'id': 'feebccc6-1eaf-4a5b-83e7-a3b468a912b8',
   'language': ['en', 'fr'],
   'last_modified': '2022-08-18T12:20:41.229839',
   'metadata_modified': '2024-11-21T01:46:52.798748',
   'mimetype': None,
   'mimetype_inner': None,
   'name': "Children's Food Project - 2020 Data",
   'name_translated': {'fr': 'Projet sur les aliments destinés aux enfants — Données 20120',
    'en': "Children's Food Project - 2020 Data"},
   'package_id': 'b1974f49-da37-4783-8705-97bfe6720a2c',
   'position': 0,
   'resource_type': 'dataset',
   'size': 10588430,
   'state': 'active',
   'unique_identifier': '',
   'url': 'https://open.canada.ca/data/dataset/b1974f49-da37-4783-8705-97bfe6720a2c/resource/feebccc6-1eaf-4a5b-83e7-a3b468a912b8/download/cfia_acia-1264-v1-cfp2020_open_data.csv',
   'url_type': 'upload',
   'validation_status': 'failure',
   'validation_timestamp': '2022-08-18T20:13:06.202973'}],
 'tags': [],
 'groups': [],
 'relationships_as_subject': [],
 'relationships_as_object': []}

In [ ]:
r_col = set(qdf.to_series(1))
s_col = set(r_df.to_series(1))

intersection = r_col & s_col
union = r_col | s_col
jaccard = round(len(intersection) / len(union), 3)
overlap = round(len(intersection) / min(len(r_col), len(s_col)), 3)
print(f'{len(intersection)=}, {len(union)=}, {jaccard=}, {overlap=}')

len(intersection)=1, len(union)=12, jaccard=0.083, overlap=1.0

In [142]:
intersection

{'Canada'}

In [ ]:
qdf.select(pl.nth(i_col)).unique().drop_nulls().join(
    r_df.select(pl.nth(0)).unique().drop_nulls(),
    left_on='Unnamed: 0', right_on='Unnamed: 0'
)

shape: (32, 1)
┌─────────────────────────────────┐
│ Unnamed: 0                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Symbols:                        │
│ Coefficient of variation (CV)   │
│ Air transportation              │
│ Other                           │
│ Maritime transportation         │
│ …                               │
│ Components may not add up to t… │
│ Rail transportation             │
│ Totals and sub-totals have bee… │
│ Size of the company             │
│ Road transportion               │
└─────────────────────────────────┘

In [ ]:
r_df.select(pl.nth(0)).unique().drop_nulls()

shape: (34, 1)
┌─────────────────────────────────┐
│ Unnamed: 0                      │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Other                           │
│ Source:                         │
│
 not applicable               │
│ F = Greater than 25.00%   too … │
│ All sizes                       │
│ …                               │
│ Table 43b                       │
│ 100 employees and more          │
│ Air transportation              │
│ Totals and sub-totals have bee… │
│ Maritime transportation         │
└─────────────────────────────────┘

In [ ]:
rcol = r_df.get_columns()[1].drop_nulls().to_list()
set(rcol).intersection(qcol)

set()

In [ ]:
# con.sql("SELECT DISTINCT(TableID) FROM OrqaIndex ORDER BY TableID LIMIT 5")
con.sql("SELECT * FROM AllTables WHERE TableId = 0 LIMIT 100")

┌─────────┬──────────┬───────┬───────────┐
│ TableId │ ColumnId │ RowId │ CellValue │
│  int32  │  int32   │ int32 │   int32   │
├─────────┼──────────┼───────┼───────────┤
│       0 │        0 │     0 │        48 │
│       0 │        0 │     1 │        48 │
│       0 │        0 │     2 │        48 │
│       0 │        0 │     3 │        48 │
│       0 │        0 │     4 │        48 │
│       0 │        0 │     5 │        48 │
│       0 │        0 │     6 │        48 │
│       0 │        0 │     7 │        48 │
│       0 │        0 │     8 │        48 │
│       0 │        0 │     9 │        48 │
│       · │        · │     · │         · │
│       · │        · │     · │         · │
│       · │        · │     · │         · │
│       0 │        0 │    30 │        48 │
│       0 │        0 │    31 │        48 │
│       0 │        0 │    32 │        48 │
│       0 │        0 │    33 │        48 │
│       0 │        0 │    34 │        48 │
│       0 │        0 │    35 │        48 │
│       0 │        0 │    36 │        48 │
│       0 │        0 │    37 │        48 │
│       0 │        0 │    38 │        48 │
│       0 │        0 │    39 │        48 │
├─────────┴──────────┴───────┴───────────┤
│ 40 rows (20 shown)           4 columns │
└────────────────────────────────────────┘

In [41]:
pl.read_parquet(f"{tables_path}/{table_ids[0]}")

shape: (80, 4)
┌──────────┬─────────────────────────────────┬─────────────────────┬───────────┐
│ Category ┆ Average Daily Count - Nova Sco… ┆ Average Daily Count ┆ Year      │
│ ---      ┆ ---                             ┆ ---                 ┆ ---       │
│ str      ┆ str                             ┆ i64                 ┆ str       │
╞══════════╪═════════════════════════════════╪═════════════════════╪═══════════╡
│ Adult    ┆ Remand - adult                  ┆ 227                 ┆ 2014-2015 │
│ Adult    ┆ Sentenced provincial custody -… ┆ 251                 ┆ 2014-2015 │
│ Adult    ┆ Other - adult                   ┆ 22                  ┆ 2014-2015 │
│ Adult    ┆ Total count - adults            ┆ 500                 ┆ 2014-2015 │
│ Adult    ┆ Remand - adult                  ┆ 223                 ┆ 2015-2016 │
│ …        ┆ …                               ┆ …                   ┆ …         │
│ Youth    ┆ Total count - youth             ┆ 7                   ┆ 2022-2023 │
│ Youth    ┆ Remand - youth                  ┆ 6                   ┆ 2023-2024 │
│ Youth    ┆ Sentenced provincial custody -… ┆ 6                   ┆ 2023-2024 │
│ Youth    ┆ Other - youth                   ┆ 1                   ┆ 2023-2024 │
│ Youth    ┆ Total count - youth             ┆ 13                  ┆ 2023-2024 │
└──────────┴─────────────────────────────────┴─────────────────────┴───────────┘