In [1]:
import json

import pandas as pd
from tqdm import tqdm
from jsonlines import jsonlines

from orqa.utils import sanitize_string

In [2]:
data_path                   = '../data'
tmp_path                    = f'{data_path}/tmp'

# the tables metadata obtained from the Open Data Canada 
# filtering by date, around July 2023
snapshot_path               = f'{data_path}/snapshot.jsonl'

# the above metadata enriched with the relative table schema
snapshot_with_schema_path   = f'{data_path}/snapshot_with_schema_also_for_zip.jsonl'

In [24]:
with jsonlines.open(snapshot_path) as reader:
    metadata = list(reader.iter())

In [25]:
print(f'Number of tables in the snapshot: {len(metadata)}')

Number of tables in the snapshot: 27752

In [6]:
[md['url'] for md in metadata[:10]]

['https://www.canada.ca/content/dam/cra-arc/migration/cra-arc/gncy/stts/gb10/pst/fnl/csv/t01ca.csv',
 'https://www.canada.ca/content/dam/eccc/migration/main/indicateurs-indicators/78a7ae2b-0d6c-4690-bab0-57652ebca282/globaltrendsbirdspeciessurvival_en.csv',
 'https://www.canada.ca/content/dam/cra-arc/migration/cra-arc/gncy/stts/opendata/bnfts/gdlntbls/cctbncbs-pfcespne-2013-eng.csv',
 'https://www150.statcan.gc.ca/n1/tbl/csv/33100655-fra.zip',
 'https://www150.statcan.gc.ca/n1/tbl/csv/33100633-fra.zip',
 'https://www150.statcan.gc.ca/n1/tbl/csv/33100653-fra.zip',
 'https://open.canada.ca/data/en/dataset/79e83e09-be72-4cec-b410-1e69aaa450f7/resource/7511b1a3-48c7-4386-ae6e-f2c4e87c6e84/download/2013-14_perchlorate_in_selected_foods_perchlorate-dans-certains-aliments.csv',
 'https://www12.statcan.gc.ca/health-sante/82-228/details/download-telecharger/all_geos/final/download.cfm?Lang=E&Format=CSV',
 'https://www150.statcan.gc.ca/n1/tbl/csv/98100289-fra.zip',
 'https://www150.statcan.gc.ca/n1/tbl/csv/33100648-fra.zip']

In [3]:
with jsonlines.open(snapshot_with_schema_path) as reader:
    metadata_with_schema = list(reader.iter())

In [4]:
print(f'Number of resources which have provided a schema: {len([csv_md for csv_md in metadata_with_schema if csv_md['schema']])}')

Number of resources which have provided a schema: 10

In [28]:
len(metadata_with_schema)

100

In [6]:
[csv_md for csv_md in metadata_with_schema if csv_md['schema']]

[{'id': '383d565c-fa77-411e-9717-0e8519926ba3',
  'package_id': 'b8964f66-ce40-4088-9209-1c29f15a345d',
  'url': 'https://data-donnees.ec.gc.ca/data/substances/monitor/impact-of-municipal-effluents-and-hydrological-regime-on-myxozoan-parasite-communities-of-fish/SLAP_SpottailShiner_MyxozoanCommunities_EN_FR.csv',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': 'SLAP SpottailShiner MyxozoanCommunities EN_FR.csv',
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2019-01-24T15:13:49.976218',
  'last_modified': None,
  'metadata_modified': '2019-01-24T15:13:49.976218',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "SLAP SpottailShiner MyxozoanCommunities EN_FR.csv", "en": "SLAP SpottailShiner MyxozoanCommunities EN_FR.csv"}',
  'language': '["en", "fr"]',
  'unique_identifier': '',
  'date_published': '',
  'datastore_contains_all_records_of_source_file': False,
  'datastore_active': False,
  'character_set': 'UTF-8',
  'data_quality': '[]',
  'schema': ['Unnamed: 0',
   'Unnamed: 1',
   'English/Anglais',
   'French/Français',
   'Unnamed: 4',
   'Unnamed: 5',
   'Unnamed: 6',
   'Unnamed: 7',
   'Unnamed: 8',
   'Unnamed: 9',
   'Unnamed: 10',
   'Unnamed: 11',
   'Unnamed: 12',
   'Unnamed: 13'],
  'get_time': 1.67291,
  'read_schema': 15.2896},
 {'id': '740ad0e6-4bf4-4490-a358-ede6a5319745',
  'package_id': 'ab74915d-a3f0-4d8d-8cd1-3d5a0e78979c',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100023-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:02.365013',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:02.365013',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Sexe',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.79331,
  'read_schema': 0.01729},
 {'id': '3bb75307-38e9-4832-baf0-d993a04b80cf',
  'package_id': '22bbf6d1-c40e-4802-88df-62b6960b348a',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100024-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:08.425414',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:08.425414',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Sexe',
   'Certaines causes de dÃ©cÃ¨s  (CIM-9)',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.82051,
  'read_schema': 3.12973},
 {'id': 'a72fd5e1-fbe6-47a6-8593-6dfa0231f98e',
  'package_id': '10e9aebc-3434-4145-9412-cd626e6bc4ac',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100022-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:04.745257',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:04.745257',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Sexe',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.83614,
  'read_schema': 0.01425},
 {'id': '4f4ad561-0dcf-4843-b1c3-d4d1f111ca97',
  'package_id': 'd8b2a449-86c8-47bc-b3e4-10648d19e913',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100027-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:10.105405',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:10.105405',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Sexe',
   'Certaines causes de dÃ©cÃ¨s (CIM-9)',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.82763,
  'read_schema': 1.7808},
 {'id': '876d4418-2ca6-430e-91fb-05eb1b384146',
  'package_id': 'f6716787-e783-49ac-8aa6-bafbea1227f6',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100029-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:13.433544',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:13.433544',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Sexe',
   'Certaines causes de dÃ©cÃ¨s (CIM-9)',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.84312,
  'read_schema': 0.01377},
 {'id': '8748303b-3612-495c-92ff-e2ab438490cc',
  'package_id': 'c611788b-8d2e-47f7-91b7-4c143703a3b2',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/13100028-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:15.198216',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:15.198216',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   "Groupe d'Ã¢ge",
   'Sexe',
   'CaractÃ©ristiques',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.83063,
  'read_schema': 2.75596},
 {'id': '8d88f76e-1bf6-4ceb-82ce-54f9ec5b15c3',
  'package_id': '088148c9-b3dd-4a4b-bb33-6ada90354014',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/33100183-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T20:17:22.455168',
  'last_modified': None,
  'metadata_modified': '2023-01-17T20:17:22.455168',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   "SystÃ¨me de classification des industries de l'AmÃ©rique du Nord (SCIAN)",
   "Taille de l'entreprise",
   'Ã\x89conomies de coÃ»ts engendrÃ©es par les innovations organisationnelles',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.80257,
  'read_schema': 0.00939},
 {'id': '89219002-2077-4952-9334-ee70c2428e5f',
  'package_id': '8f1406dc-770d-44bc-a47a-4719757d65ef',
  'url': 'https://data-donnees.ec.gc.ca/data/substances/monitor/spatial-distribution-and-seasonal-variation-of-epiphytic-cyanobacteria-filamentous-algae-and-macrophytes-in-the-st.-lawrence-river/SLAP_CyanobacteriaBiomass2007_EN_FR.csv',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': 'SLAP_CyanobacteriaBiomass 2007_EN_FR.csv',
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2019-08-28T17:23:32.250180',
  'last_modified': None,
  'metadata_modified': '2019-08-28T17:23:32.250180',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "SLAP_CyanobacteriaBiomass 2007_EN_FR.csv", "en": "SLAP_CyanobacteriaBiomass 2007_EN_FR.csv"}',
  'language': '["en", "fr"]',
  'unique_identifier': '',
  'date_published': '',
  'datastore_contains_all_records_of_source_file': False,
  'datastore_active': False,
  'character_set': 'UTF-8',
  'data_quality': '[]',
  'schema': ['Unnamed: 0',
   'Unnamed: 1',
   'English/Anglais',
   'French/Français',
   'Unnamed: 4',
   'Unnamed: 5',
   'Unnamed: 6',
   'Unnamed: 7',
   'Unnamed: 8',
   'Unnamed: 9',
   'Unnamed: 10',
   'Unnamed: 11',
   'Unnamed: 12',
   'Unnamed: 13',
   'Unnamed: 14',
   'Unnamed: 15',
   'Unnamed: 16',
   'Unnamed: 17'],
  'get_time': 1.35915,
  'read_schema': 15.69405},
 {'id': '88fef979-9857-4313-ac8a-59c8cf93e73e',
  'package_id': '33f1e188-2e2d-4ef7-a9f2-c431b3301439',
  'url': 'https://www150.statcan.gc.ca/n1/tbl/csv/23100165-fra.zip',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': None,
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2023-01-17T21:50:08.774937',
  'last_modified': None,
  'metadata_modified': '2023-01-17T21:50:08.774937',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Ensembles de donn\\u00e9es", "en": "Dataset"}',
  'data_quality': '[]',
  'language': '["fr"]',
  'schema': ['ï»¿"PÃ\x89RIODE DE RÃ\x89FÃ\x89RENCE"',
   'GÃ\x89O',
   'DGUID',
   'Type de vÃ©hicule',
   'Heure du jour',
   'UNITÃ\x89 DE MESURE',
   "IDENTIFICATEUR D'UNITÃ\x89 DE MESURE",
   'FACTEUR SCALAIRE',
   'IDENTIFICATEUR SCALAIRE',
   'VECTEUR',
   'COORDONNÃ\x89ES',
   'VALEUR',
   'STATUS',
   'SYMBOLE',
   'TERMINÃ\x89',
   'DÃ\x89CIMALES'],
  'get_time': 0.82847,
  'read_schema': 0.00746}]

In [ ]:
for csv_md in metadata:
    if 'schema' not in csv_md:
        csv_md['schema'] = []

### Load the Clusters created from the Tables zipped into LakeBench

In [11]:
join_clusters_path  = f'{data_path}/join/clusters/clusters_CAN.json'
union_clusters_path = f'{data_path}/union/clusters/clusters_CAN.json'

join_schema_path    = f'{data_path}/join/schema/tables_schema_CAN.json'
union_schema_path   = f'{data_path}/union/schema/tables_schema_CAN.json' 

with open(join_clusters_path) as fr:
    join_clusters = json.load(fr)

with open(union_clusters_path) as fr:
    union_clusters = json.load(fr)

with open(join_schema_path) as fr:
    join_tables_schema = json.load(fr)

with open(union_schema_path) as fr:
    union_tables_schema = json.load(fr)

In [12]:
from itertools import chain


join_all_attributes = set(chain(*join_tables_schema.values()))
union_all_attributes = set(chain(*union_tables_schema.values()))
len(join_all_attributes), len(union_all_attributes)

(1336, 2815)

In [ ]:
# keep only tables which have a not-empty schema
metadata = list(filter(lambda md: md['schema'], metadata))
len(metadata)

13566

In [ ]:
# clean the schema of the tables from the snapshot
for md in metadata:
    md['schema'] = list(map(sanitize_string, md['schema']))

In [19]:
# takes the tables whose schema is fully contained into the join or union macrosets
tables_in_join  = list(filter(lambda md: set(md['schema']).intersection(join_all_attributes) == set(md['schema']), metadata))
tables_in_union = list(filter(lambda md: set(md['schema']).intersection(union_all_attributes) == set(md['schema']), metadata))

len(tables_in_join), len(tables_in_union)

(138, 204)

In [20]:
# we can focus only on the tables in the union case
# because the attributes from the union tables seem to be a superset of the join case
len(set(md['id'] for md in tables_in_join).difference(set(md['id'] for md in tables_in_union)))

0

In [21]:
tables_in_union[:1]

[{'id': '1d12079c-ae9b-49f1-bd65-56a5dc984673',
  'package_id': '53f8ab93-ab62-486a-b563-1381224fcbc7',
  'url': 'https://ised-isde.canada.ca/site/canadian-importers-database/sites/default/files/attachments/HS10Description2019.csv',
  'format': 'CSV',
  'description': '',
  'hash': '',
  'position': 0,
  'name': 'HS10 Description',
  'resource_type': 'dataset',
  'mimetype': None,
  'mimetype_inner': None,
  'size': None,
  'created': '2020-12-07T21:50:49.781530',
  'last_modified': None,
  'metadata_modified': '2020-12-07T21:50:49.781530',
  'cache_url': None,
  'cache_last_updated': None,
  'url_type': None,
  'state': 'active',
  'name_translated': '{"fr": "Description SH10", "en": "HS10 Description"}',
  'language': '["en", "fr"]',
  'date_published': '',
  'unique_identifier': '',
  'validation_timestamp': '',
  'datastore_contains_all_records_of_source_file': False,
  'validation_status': '',
  'datastore_active': False,
  'character_set': '',
  'data_quality': '[]',
  'schema': ['hs10_sh10', 'description_eng', 'description_fra']}]

In [22]:
union_clusters

{'max_num_of_cooccurrences': 1,
 'num_perm': 16,
 'l': 4,
 'k': 200,
 'clusters': [{'key': 0,
   'schema': ['sector',
    'type_of_power_plant',
    'canadian_portfolio_securities',
    'type_of_employee',
    'service_detail',
    'sector_accounts',
    'institution',
    'number_of_owners',
    'period_of_construction',
    'release',
    'type_of_case',
    'jurisdiction',
    'index',
    'payment_collection_rate',
    'inputs_outputs',
    'stormwater_assets',
    'mobility_indicators',
    'measures',
    'age_of_victim',
    'seasonality',
    'personal_protective_equipment_or_supplies',
    'interjurisdictional_support_order_status',
    'owner_characteristics_at_the_property_level',
    'commodity',
    'fuel_type',
    'machinery_and_equipment,_domestic_and_imported',
    'incorporation_status',
    'statistics',
    'overtime',
    'products',
    'import_and_export_major_groups_and_standard_international_trade_classification_(sitc_revision_3)',
    'credit_liabilities_of_private_non_financial_corporations',
    'employment_size',
    'scalar_factor',
    'satisfaction_with_dwelling_and_neighbourhood',
    'geo',
    'selected_trades',
    'types_of_revenues',
    'value_range',
    'percentage_range_of_full_time_employees',
    'location_of_raw_materials_and_components',
    'supplier_type',
    'i__ref_date__',
    'type_of_fire_incident',
    'monthly',
    'length_of_time_served',
    'seasonal_adjustment',
    'selected_sociodemographic_characteristics',
    'type_of_building',
    'co_operative_arrangements',
    'work_integrated_learning_(wil)_participation',
    'estimates',
    'nature_of_research_and_development',
    'year_of_vehicle_model',
    'work_absence_statistics',
    'ages_group',
    'length_of_time_expected_to_continue_being_an_obstacle',
    'airports',
    'activity_status',
    'assets',
    'valuation',
    'type_of_control',
    'type_of_transaction',
    'sources_of_information',
    'household_spending,_miscellaneous_(legal,_financial)',
    'type_of_asset',
    'indigenous_identity',
    'investment_and_capital',
    'correctional_services',
    'year(s)_after_certification',
    'number_of_properties_owned_by_the_property_owner',
    'value',
    'obstacles',
    'interprovincial_activities_conducted_over_the_last_12_months',
    'residency_status',
    'type_of_farm_items',
    'production_and_disposition',
    'principal_trading_areas',
    'selected_causes_of_death',
    'types_of_expenditures',
    'income_taxes,_deductions_and_benefits',
    'violations',
    'type_of_earners',
    'aboriginal_status',
    'presence_of_children_in_household',
    'type_of_industry',
    'owner_occupied_property_type',
    'characteristics',
    'weighting',
    'farm_area,_production,_value',
    'waitlist_status_including_length_of_time',
    'national_occupational_classification_(noc)',
    'transmission',
    'household_food_insecurity_measures',
    'non_owner_occupied_property_type',
    'new_machinery_or_equipment',
    'household_expenditures,_summary_level_categories',
    'number_of_years_since_case_initiation',
    'statistic',
    'basis',
    'uom',
    "manufacturers'_opinions",
    'commodities',
    'after_tax_income_quintile',
    'type_of_plant',
    'percentage_of_employees',
    'labour_force_characteristics',
    'pipeline_movements',
    'national_occupational_classification_for_statistics_(noc_s)',
    'tenure_including_social_and_affordable_housing',
    'adjustments',
    'body_mass_index_(bmi)',
    'source_of_ignition',
    'household_food_insecurity_status',
    'business_characteristics',
    'unit_of_measure',
    'standard_industrial_classification,_1960_(sic)',
    'sales,_price_and_volume',
    'awareness_of_trade_agreement',
    'liquid_hydrocarbons',
    'type_of_expenditures',
    'supply_and_disposition',
    'obstacles_for_the_business_or_organization',
    'business_or_organization_plans_to_take_any_new_or_additional_cybersecurity_actions',
    'multifactor_productivity_and_related_variables',
    'primary_competition_and_most_important_competitive_strength_related_to_businesses_or_organizations_that_exported_or_sold_goods_or_services_to_the_united_states',
    'type_of_business_unit',
    'location_indicator',
    'standard_industrial_classification,_1980_(sic)',
    'business_or_organization_plans',
    'industry_of_purchase',
    'visible_minority',
    'decimals',
    'indicators',
    'business_or_organization_directly_sourced_its_inputs,_products_or_supplies_within_canada',
    'scalar_id',
    'type_of_municipality_by_population_size',
    'financing_characteristic',
    'affirmation_of_novelty',
    'employment_categories',
    'trade_group',
    'economic_family_type',
    'household_spending,_recreation',
    'facility_ownership',
    'type_of_employees',
    'percentage_of_on_site_employees_tested_using_a_covid_19_rapid_test_kit_at_least_once_over_the_last_month',
    'level_of_court',
    'trading_area',
    'types_of_funds_and_functions',
    'agreements',
    'trade_agreement',
    'income_statement',
    'linguistic_profile',
    'dguid',
    'business_or_organization_ability_to_take_on_more_debt',
    'uom_id',
    'field_of_study',
    'year_of_completed_construction',
    'degree_of_importance',
    'north_american_industry_classification_system_(naics)',
    'coordinate',
    'rank',
    'domestic_and_international_itinerant_movements',
    'service_type',
    'trade',
    "census_subdivision_area_(csd)_of_the_owner's_other_properties",
    'characteristics_of_tax_filers_with_investment_income',
    'gender_of_victim',
    'companies',
    'north_american_product_classification_system_(napcs)',
    'industry',
    'type_of_instrument',
    'act_or_omission',
    'supply_and_demand_characteristics',
    'expected_sales_change_from_october_to_december_2021_compared_with_october_to_december_2019',
    'percentage_range_of_expenditures',
    'selected_sites_of_cancer',
    'vector',
    'goods_and_services_(products)',
    'principal_statistics',
    'hourly_wages',
    'residency_participation',
    'financial_characteristics',
    'components',
    'types_of_universities',
    'status',
    'health_profile',
    'legal_type',
    'recruitment,_retention_and_training_plans',
    'occupations',
    'novelty_of_product',
    'reasons_for_co_operation',
    'household_tenure',
    'business_or_organization_plans_to_expand,_restructure,_or_acquire_or_invest_in_other_businesses_or_organizations',
    'variables',
    'structural_type_of_dwelling',
    'type_of_expenditure',
    'units_of_measure',
    'level_of_study',
    'trading_partners',
    'type_of_work',
    'individuals_and_income',
    'property_type',
    'wealth',
    'index_base_period',
    'elapsed_time_from_case_initiation_to_first_disposition',
    'location_of_supplier',
    "census_metropolitain_area_(cma)_of_the_owner's_other_properties",
    'employment_flow_rate',
    'change_in_average_wages_paid',
    'remaining_maturity',
    'other_livestock',
    'level_of_difficulty_expected_in_procuring_personal_protective_equipment_or_supplies',
    'country_of_control',
    'custodial_and_community_admissions',
    'type_of_beneficiary',
    'sex',
    'data_type',
    'north_american_industry_classification_system_(naics)_sector',
    'activity_sector',
    'age_at_time_of_death',
    'enterprise_size_of_employment',
    'off_reserve_aboriginal_profile',
    'government_of_canada_direct_securities_and_loans',
    'major_sub_trade_group',
    'selected_causes_of_death_(icd_9)',
    'predominant_group_of_residents_and_size_of_facility',
    'environmental_practices_in_place_or_planned_to_be_implemented_over_the_next_12_months',
    'area_of_residence',
    'index_type',
    'type_of_operation',
    'merchandise_import_and_export_sectors_and_sub_sectors',
    'income,_consumption_and_savings',
    'types_of_funds',
    'novelty_of_process'],
   'ids': ['CAN_CSV0000000000027207.csv',
    'CAN_CSV0000000000005788.csv',
    'CAN_CSV0000000000013072.csv',
    'CAN_CSV0000000000001185.csv',
    'CAN_CSV0000000000000735.csv',
    'CAN_CSV0000000000005322.csv',
    'CAN_CSV0000000000012697.csv',
    'CAN_CSV0000000000000965.csv',
    'CAN_CSV0000000000004799.csv',
    'CAN_CSV0000000000001152.csv',
    'CAN_CSV0000000000006035.csv',
    'CAN_CSV0000000000012448.csv',
    'CAN_CSV0000000000012922.csv',
    'CAN_CSV0000000000005426.csv',
    'CAN_CSV0000000000000953.csv',
    'CAN_CSV0000000000006677.csv',
    'CAN_CSV0000000000015682.csv',
    'CAN_CSV0000000000000823.csv',
    'CAN_CSV0000000000005395.csv',
    'CAN_CSV0000000000000772.csv',
    'CAN_CSV0000000000001148.csv',
    'CAN_CSV0000000000001193.csv',
    'CAN_CSV0000000000027206.csv',
    'CAN_CSV0000000000000709.csv',
    'CAN_CSV0000000000012496.csv',
    'CAN_CSV0000000000006635.csv',
    'CAN_CSV0000000000012897.csv',
    'CAN_CSV0000000000013186.csv',
    'CAN_CSV0000000000007109.csv',
    'CAN_CSV0000000000006997.csv',
    'CAN_CSV0000000000012911.csv',
    'CAN_CSV0000000000015707.csv',
    'CAN_CSV0000000000000822.csv',
    'CAN_CSV0000000000004798.csv',
    'CAN_CSV0000000000012391.csv',
    'CAN_CSV0000000000005811.csv',
    'CAN_CSV0000000000012943.csv',
    'CAN_CSV0000000000013576.csv',
    'CAN_CSV0000000000006881.csv',
    'CAN_CSV0000000000007059.csv',
    'CAN_CSV0000000000000828.csv',
    'CAN_CSV0000000000000613.csv',
    'CAN_CSV0000000000004940.csv',
    'CAN_CSV0000000000012515.csv',
    'CAN_CSV0000000000004796.csv',
    'CAN_CSV0000000000006919.csv',
    'CAN_CSV0000000000005307.csv',
    'CAN_CSV0000000000000737.csv',
    'CAN_CSV0000000000000753.csv',
    'CAN_CSV0000000000001241.csv',
    'CAN_CSV0000000000001084.csv',
    'CAN_CSV0000000000001248.csv',
    'CAN_CSV0000000000002293.csv',
    'CAN_CSV0000000000005740.csv',
    'CAN_CSV0000000000012842.csv',
    'CAN_CSV0000000000005583.csv',
    'CAN_CSV0000000000000775.csv',
    'CAN_CSV0000000000005748.csv',
    'CAN_CSV0000000000001072.csv',
    'CAN_CSV0000000000005138.csv',
    'CAN_CSV0000000000027078.csv',
    'CAN_CSV0000000000014515.csv',
    'CAN_CSV0000000000012996.csv',
    'CAN_CSV0000000000006845.csv',
    'CAN_CSV0000000000013926.csv',
    'CAN_CSV0000000000005930.csv',
    'CAN_CSV0000000000005744.csv',
    'CAN_CSV0000000000001128.csv',
    'CAN_CSV0000000000000997.csv',
    'CAN_CSV0000000000005486.csv',
    'CAN_CSV0000000000000666.csv',
    'CAN_CSV0000000000013439.csv',
    'CAN_CSV0000000000005706.csv',
    'CAN_CSV0000000000006894.csv',
    'CAN_CSV0000000000002294.csv',
    'CAN_CSV0000000000000687.csv',
    'CAN_CSV0000000000005048.csv',
    'CAN_CSV0000000000005775.csv',
    'CAN_CSV0000000000012865.csv',
    'CAN_CSV0000000000005854.csv',
    'CAN_CSV0000000000001024.csv',
    'CAN_CSV0000000000013327.csv',
    'CAN_CSV0000000000005297.csv',
    'CAN_CSV0000000000005659.csv',
    'CAN_CSV0000000000002295.csv',
    'CAN_CSV0000000000005369.csv',
    'CAN_CSV0000000000012599.csv',
    'CAN_CSV0000000000000686.csv',
    'CAN_CSV0000000000006434.csv',
    'CAN_CSV0000000000000977.csv',
    'CAN_CSV0000000000001033.csv',
    'CAN_CSV0000000000013596.csv',
    'CAN_CSV0000000000004794.csv',
    'CAN_CSV0000000000005446.csv',
    'CAN_CSV0000000000001186.csv',
    'CAN_CSV0000000000012497.csv',
    'CAN_CSV0000000000015766.csv',
    'CAN_CSV0000000000001181.csv',
    'CAN_CSV0000000000005812.csv',
    'CAN_CSV0000000000013375.csv',
    'CAN_CSV0000000000004797.csv',
    'CAN_CSV0000000000013036.csv',
    'CAN_CSV0000000000005448.csv',
    'CAN_CSV0000000000000945.csv',
    'CAN_CSV0000000000012766.csv',
    'CAN_CSV0000000000004792.csv',
    'CAN_CSV0000000000000719.csv',
    'CAN_CSV0000000000007114.csv',
    'CAN_CSV0000000000000556.csv',
    'CAN_CSV0000000000001247.csv',
    'CAN_CSV0000000000000861.csv',
    'CAN_CSV0000000000005842.csv',
    'CAN_CSV0000000000006868.csv',
    'CAN_CSV0000000000012528.csv',
    'CAN_CSV0000000000000857.csv',
    'CAN_CSV0000000000001013.csv',
    'CAN_CSV0000000000000724.csv',
    'CAN_CSV0000000000027057.csv',
    'CAN_CSV0000000000000771.csv',
    'CAN_CSV0000000000012523.csv',
    'CAN_CSV0000000000013940.csv',
    'CAN_CSV0000000000012765.csv',
    'CAN_CSV0000000000006672.csv',
    'CAN_CSV0000000000015721.csv',
    'CAN_CSV0000000000000762.csv',
    'CAN_CSV0000000000002418.csv',
    'CAN_CSV0000000000012928.csv',
    'CAN_CSV0000000000027218.csv',
    'CAN_CSV0000000000013763.csv',
    'CAN_CSV0000000000012767.csv',
    'CAN_CSV0000000000001195.csv',
    'CAN_CSV0000000000004791.csv',
    'CAN_CSV0000000000006897.csv',
    'CAN_CSV0000000000000885.csv',
    'CAN_CSV0000000000000730.csv',
    'CAN_CSV0000000000000827.csv',
    'CAN_CSV0000000000005720.csv',
    'CAN_CSV0000000000027157.csv',
    'CAN_CSV0000000000013440.csv',
    'CAN_CSV0000000000000960.csv',
    'CAN_CSV0000000000015776.csv',
    'CAN_CSV0000000000012769.csv',
    'CAN_CSV0000000000012495.csv',
    'CAN_CSV0000000000000871.csv',
    'CAN_CSV0000000000006624.csv',
    'CAN_CSV0000000000006923.csv',
    'CAN_CSV0000000000014397.csv',
    'CAN_CSV0000000000006623.csv',
    'CAN_CSV0000000000013912.csv',
    'CAN_CSV0000000000000680.csv',
    'CAN_CSV0000000000015570.csv',
    'CAN_CSV0000000000015780.csv',
    'CAN_CSV0000000000005891.csv',
    'CAN_CSV0000000000027162.csv',
    'CAN_CSV0000000000001074.csv',
    'CAN_CSV0000000000006863.csv',
    'CAN_CSV0000000000012839.csv',
    'CAN_CSV0000000000012785.csv',
    'CAN_CSV0000000000015797.csv',
    'CAN_CSV0000000000005070.csv',
    'CAN_CSV0000000000000883.csv',
    'CAN_CSV0000000000012900.csv',
    'CAN_CSV0000000000004707.csv',
    'CAN_CSV0000000000006657.csv',
    'CAN_CSV0000000000013328.csv',
    'CAN_CSV0000000000015712.csv',
    'CAN_CSV0000000000001136.csv',
    'CAN_CSV0000000000013736.csv',
    'CAN_CSV0000000000013782.csv',
    'CAN_CSV0000000000013319.csv',
    'CAN_CSV0000000000005430.csv',
    'CAN_CSV0000000000004746.csv',
    'CAN_CSV0000000000012732.csv',
    'CAN_CSV0000000000012792.csv',
    'CAN_CSV0000000000027081.csv',
    'CAN_CSV0000000000001053.csv',
    'CAN_CSV0000000000005658.csv',
    'CAN_CSV0000000000000974.csv',
    'CAN_CSV0000000000013732.csv',
    'CAN_CSV0000000000000964.csv',
    'CAN_CSV0000000000013334.csv',
    'CAN_CSV0000000000013739.csv',
    'CAN_CSV0000000000001045.csv',
    'CAN_CSV0000000000000949.csv',
    'CAN_CSV0000000000001149.csv',
    'CAN_CSV0000000000006934.csv',
    'CAN_CSV0000000000000905.csv',
    'CAN_CSV0000000000000777.csv',
    'CAN_CSV0000000000006650.csv',
    'CAN_CSV0000000000005766.csv',
    'CAN_CSV0000000000000712.csv',
    'CAN_CSV0000000000012844.csv',
    'CAN_CSV0000000000012501.csv',
    'CAN_CSV0000000000006630.csv',
    'CAN_CSV0000000000013792.csv',
    'CAN_CSV0000000000002266.csv',
    'CAN_CSV0000000000001198.csv',
    'CAN_CSV0000000000001119.csv',
    'CAN_CSV0000000000000825.csv',
    'CAN_CSV0000000000012875.csv']},
  {'key': 1,
   'schema': ['sector',
    'age_group',
    'capital_and_repair_expenditures',
    'probability_of_depression',
    'breast_self_examinations',
    'price_index',
    'degree_of_specialization',
    'arrear_status_at_end_of_fiscal_year',
    'research_and_development_characteristics',
    'smoking_status',
    'reason_for_part_time_work',
    'type_of_structure',
    'field_of_science_or_technology',
    'overall_physical_condition_of_assets',
    'commodity',
    'fuel_type',
    'machinery_and_equipment,_domestic_and_imported',
    'statistics',
    'products',
    'industry_expenditures',
    'scalar_factor',
    'selected_trades',
    'geo',
    'dividend_and_interest_income',
    'i__ref_date__',
    'aboriginal_identity',
    'population_centre_and_rural_areas',
    'index_year',
    'seasonal_adjustment',
    'type_of_building',
    'bridge_and_tunnel_assets',
    'home_care_utilization',
    'year_of_vehicle_model',
    'public_sector_components',
    'healthy_aging_indicators',
    'patient_satisfaction___community_based_health_care',
    'assets',
    'major_departments_and_agencies',
    'category',
    'primary_types_of_cancer_',
    'performing_sector',
    'smoking',
    'construction_trades',
    'class_of_worker',
    'receipts,_payments_and_balances',
    'trends',
    'value',
    'high_blood_pressure',
    'payments_made_or_received_for_intellectual_property_and_other_technology_related_services',
    'characteristics',
    'weighting',
    'area',
    'national_occupational_classification_(noc)',
    'intellectual_property_and_other_technology_related_services',
    'display_value',
    'basis',
    'uom',
    'sociodemographic_characteristics',
    'science_and_technology_components',
    'unmet_health_care_needs',
    'labour_force_characteristics',
    'body_mass_index_(bmi),_canadian_standard',
    'income_indicators',
    'selected_sites_of_cancer_(icd_o_3)',
    'indicator',
    'population_group',
    'unit_of_measure',
    'supply_and_disposition',
    'self_rated_health',
    'making_handcrafted_goods',
    'type_of_wage_indexes',
    'gender',
    'industry_of_purchase',
    'decimals',
    'indicators',
    'trade_group',
    'scalar_id',
    'type_of_municipality_by_population_size',
    'selected_balance_sheet_and_income_statement_components',
    'revenue_class',
    'reasons_for_making_handcrafted_goods',
    'adjustments',
    'household_food_security_status',
    'age_interval',
    'satisfaction_with_current_job',
    'indigenous_group',
    'projection_scenario',
    'frequency_of_having_5_or_more_drinks_on_one_occasion',
    'activity_limitation',
    'adjustment',
    'dguid',
    'flows_and_stocks',
    'uom_id',
    'functional_health_status',
    'year_of_completed_construction',
    'colorectal_cancer_screeening',
    'north_american_industry_classification_system_(naics)',
    'influenza_immunization',
    'coordinate',
    'union_coverage',
    'north_american_product_classification_system_(napcs)',
    'pain_or_discomfort_by_severity',
    'perceived_mental_health_and_suicidal_thoughts',
    'demographic_characteristics',
    'selected_farm_types',
    'statement_of_operations_and_balance_sheet',
    'self_esteem',
    'vector',
    'agricultural_sales',
    'contact_with_health_professionals_about_mental_health',
    'principal_statistics',
    'regular_amount_due_to_beneficiary',
    'status',
    'components',
    'implicit_price_index_components',
    'mismatch_of_skills_for_current_job',
    'year_in_program',
    'components_of_population_growth',
    'alcohol_dependence',
    'prices',
    'type_of_sales',
    'variables',
    'program_field',
    'access_to_and_use_of_health_care_services',
    'element',
    'risk_level_of_depression',
    'country_of_control',
    'vitamin_and_mineral_supplements_consumption',
    'pain_or_discomfort_that_affects_activities',
    'sex',
    'standard_industrial_classification,_1970_(sic)',
    'activity_sector',
    'major_sub_trade_group',
    'current_account_and_capital_account',
    'countries_or_regions',
    'index_type',
    'domains',
    'merchandise_import_and_export_sectors_and_sub_sectors'],
   'ids': ['CAN_CSV0000000000001117.csv',
    'CAN_CSV0000000000027220.csv',
    'CAN_CSV0000000000014469.csv',
    'CAN_CSV0000000000006690.csv',
    'CAN_CSV0000000000013954.csv',
    'CAN_CSV0000000000015770.csv',
    'CAN_CSV0000000000005731.csv',
    'CAN_CSV0000000000027254.csv',
    'CAN_CSV0000000000002256.csv',
    'CAN_CSV0000000000005415.csv',
    'CAN_CSV0000000000027281.csv',
    'CAN_CSV0000000000027168.csv',
    'CAN_CSV0000000000012460.csv',
    'CAN_CSV0000000000013142.csv',
    'CAN_CSV0000000000027244.csv',
    'CAN_CSV0000000000005108.csv',
    'CAN_CSV0000000000027217.csv',
    'CAN_CSV0000000000014316.csv',
    'CAN_CSV0000000000006714.csv',
    'CAN_CSV0000000000014474.csv',
    'CAN_CSV0000000000014476.csv',
    'CAN_CSV0000000000012606.csv',
    'CAN_CSV0000000000000554.csv',
    'CAN_CSV0000000000012455.csv',

In [26]:
from collections import defaultdict


candidates = defaultdict(list)

# for each snapshot table, explore each cluster:
# if there is any cluster table which has an identical schema, save it
for md in tqdm(tables_in_union):
    schema = set(md['schema'])
    url = md['url']
    tid = md['id']

    for cluster in tqdm(union_clusters['clusters'], position=1, leave=False):
        if not schema.intersection(cluster['schema']) == schema:
            continue
        for csv_id in cluster['ids']:
            if schema == set(union_tables_schema[csv_id]):
                candidates[tid].append(csv_id)

100%|██████████| 204/204 [00:00<00:00, 315.32it/s]

In [27]:
remote_table_ids = list(candidates.keys())
len(remote_table_ids)

139

In [28]:
tid = remote_table_ids[138]
candidates[tid]

['CAN_CSV0000000000004354.csv', 'CAN_CSV0000000000016880.csv']

In [29]:
md = [t for t in tables_in_union if t['id'] == tid][0]
md

{'id': '6095d1b8-ebbb-46d2-9b47-5b6d64f8d4ed',
 'package_id': 'f7371bb6-a7f7-49e7-b072-da95cddd2379',
 'url': 'https://www.neb-one.gc.ca/open/energy/energyfutures2016/primary-energy-demand-2016.csv',
 'format': 'CSV',
 'description': '',
 'hash': '',
 'position': 60,
 'name': 'Primary Energy Demand 2016',
 'resource_type': 'dataset',
 'mimetype': None,
 'mimetype_inner': None,
 'size': None,
 'created': '2019-02-27T21:40:46.957239',
 'last_modified': None,
 'metadata_modified': '2019-02-27T21:40:46.957239',
 'cache_url': None,
 'cache_last_updated': None,
 'url_type': None,
 'state': 'active',
 'related_type': '',
 'name_translated': '{"fr": "demande-d-energie-primaire-2016", "en": "Primary Energy Demand 2016"}',
 'language': '["en"]',
 'unique_identifier': '',
 'date_published': '',
 'related_relationship': '',
 'datastore_active': False,
 'character_set': '',
 'data_quality': '[]',
 'schema': ['sector',
  'case',
  'region',
  'variable_english',
  'year',
  'value',
  'sector_1']}

In [30]:
remote_table = pd.read_csv(md['url'], encoding_errors='ignore')
remote_table

,Sector,Case,Region,Variable_English,Year,Value,Sector.1
0,Electric and Steam Generation,Reference,Canada,Natural Gas,2005,401.8711,Electric and Steam Generation
1,Electric and Steam Generation,Reference,Canada,Natural Gas,2006,432.9016,Electric and Steam Generation
2,Electric and Steam Generation,Reference,Canada,Natural Gas,2007,434.1760,Electric and Steam Generation
3,Electric and Steam Generation,Reference,Canada,Natural Gas,2008,458.2970,Electric and Steam Generation
4,Electric and Steam Generation,Reference,Canada,Natural Gas,2009,437.5902,Electric and Steam Generation
...,...,...,...,...,...,...,...
42331,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2036,0.3401,Primary Demand
42332,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2037,0.3426,Primary Demand
42333,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2038,0.3452,Primary Demand
42334,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2039,0.3385,Primary Demand
42335,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2040,0.3418,Primary Demand

In [ ]:
import zipfile

local_table = None

# for each table which is a candidate for a mapping with 
# the current remote table, look if the two are identical
with zipfile.ZipFile(f'{data_path}/datasets/datasets_CAN.zip') as z:
    for candidate in candidates[tid]:
        with z.open(f'datasets_CAN/{candidate}') as fr:
            table = pd.read_csv(fr)
            print(table.shape)
            if table.equals(remote_table):
                print('found ', candidate, table.equals(remote_table))
                local_table = table
local_table

(42336, 7)
found  CAN_CSV0000000000004354.csv True
(42336, 7)
found  CAN_CSV0000000000016880.csv True

,Sector,Case,Region,Variable_English,Year,Value,Sector.1
0,Electric and Steam Generation,Reference,Canada,Natural Gas,2005,401.8711,Electric and Steam Generation
1,Electric and Steam Generation,Reference,Canada,Natural Gas,2006,432.9016,Electric and Steam Generation
2,Electric and Steam Generation,Reference,Canada,Natural Gas,2007,434.1760,Electric and Steam Generation
3,Electric and Steam Generation,Reference,Canada,Natural Gas,2008,458.2970,Electric and Steam Generation
4,Electric and Steam Generation,Reference,Canada,Natural Gas,2009,437.5902,Electric and Steam Generation
...,...,...,...,...,...,...,...
42331,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2036,0.3401,Primary Demand
42332,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2037,0.3426,Primary Demand
42333,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2038,0.3452,Primary Demand
42334,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2039,0.3385,Primary Demand
42335,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2040,0.3418,Primary Demand

In [32]:
table

,Sector,Case,Region,Variable_English,Year,Value,Sector.1
0,Electric and Steam Generation,Reference,Canada,Natural Gas,2005,401.8711,Electric and Steam Generation
1,Electric and Steam Generation,Reference,Canada,Natural Gas,2006,432.9016,Electric and Steam Generation
2,Electric and Steam Generation,Reference,Canada,Natural Gas,2007,434.1760,Electric and Steam Generation
3,Electric and Steam Generation,Reference,Canada,Natural Gas,2008,458.2970,Electric and Steam Generation
4,Electric and Steam Generation,Reference,Canada,Natural Gas,2009,437.5902,Electric and Steam Generation
...,...,...,...,...,...,...,...
42331,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2036,0.3401,Primary Demand
42332,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2037,0.3426,Primary Demand
42333,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2038,0.3452,Primary Demand
42334,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2039,0.3385,Primary Demand
42335,Primary Demand,Constrained,Yukon,Other Renewables and Landfill Gas,2040,0.3418,Primary Demand

In [34]:
# if the remote table and the found local table are identical, this should result into an empty data frame
remote_table[~remote_table.apply(tuple, 1).isin(local_table.apply(tuple, 1))]

Empty DataFrame
Columns: [Sector, Case, Region, Variable_English, Year, Value, Sector.1]
Index: []